### ISSUE TITLE
Add more assets to Spacewalk UI

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#106]
As a spacewalk user, I should be able to see in total 4 assets.

# Acceptance criteria
* Show USDC, XLM, TZS and BRL in the "To Pendulum" asset selection dropdown
* Show aUSDC, aXLM, aTZS and aBRL in the "Back to stellar" asset selection dropdown
* The respective asset should also be displayed for Bridge fee and the respective dailog boxes if a txn is created for that asset.

**Comment by prayagd** [comment]
@gonzamontiel Please let me know if this ticket is clear.

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/106?planning-poker) with Zenhub @gonzamontiel

**Comment by gonzamontiel** [comment]
I think I am missing the complete asset definition here. Assets are usually an AlphaNum4 or AlphaNum12 code, and an issuer.

**Comment by prayagd** [comment]
@ebma I know the transaction is being executed to add these new assets, But is there way can you share these AlphaNum4 or AlphaNum12 code?

**Comment by ebma** [comment]
This ticket can probably be closed because the assets are not hard-coded but fetched and shown based on the registered vaults. Thus, once we register the vault clients on Amplitude for XLM, TZS and BRL, these assets will automatically be shown in the selector. 

Just to be safe jet's wait and confirm once the vault clients are registered before closing this.

**Comment by prayagd** [comment]
@ebma Noted

**Comment by erasmus** [comment]
@prayagd can we check this now?

**Comment by prayagd** [comment]
It worked for the USDC and XLM but as we are waiting for two more assets to be added ie BRL and TZS. Once those are done will close this.

**Comment by prayagd** [comment]
@gonzamontiel @ebma Closing this as all the planned assets are now added to the spacewalk UI.
