### ISSUE TITLE
Show asset max issuable and max redeem capacity. 

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#107]
As a spacewalk user, i should be able to see the max amount of asset i can issue or redeem

# Acceptance criteria
* In the "To Amplitude" view. 
* In the box where all txn details are dispalyed show "Max issuable" when the user selects a asset. 
* Show this amount in the asset that was selected to issue
* In the "Back to stellar" view
* In the box where all txn details are dispalyed show "Max redeemable" when the user selects a asset
* Show this amount in the asset that was selected to redeem.

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/107?planning-poker) with Zenhub @gonzamontiel

**Comment by gonzamontiel** [comment]
It is clear enough. Sometimes, to avoid confusions, It would be nice to take a screenshot and use an arrow to indicate where are you picturing that value. I can also use my own criteria, but it may lead to an unnecessary back and forth.

**Comment by prayagd** [comment]
Noted.
