### ISSUE TITLE
Show vault details in the vault dropdown

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#108]
As a spacewalk user, I should be able to see the vault capacity when selecting the vault. 

# Acceptance criteria
* While issuing/redeeming, if i select "Manually select vault"
* Currently only the vault address is shown
* Show the amount of issuable tokens of the vault in the asset the user wants to issue/redeem.

**Comment by prayagd** [comment]
@gonzamontiel Please let me know if this is clear, will get you the designs for this.

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/108?planning-poker) with Zenhub @gonzamontiel

**Comment by gonzamontiel** [comment]
I think it is clear, added my complexity assuming the designs aren't too crazy.

**Comment by prayagd** [comment]
@gonzamontiel Here is the design https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=754-1618&t=UWe7fcwJskuU4O7g-4
