### ISSUE TITLE
Create swap transaction for Nabla swap

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#110]
As a 0xAmber user, i should be able to do a swap transaction. 

## Acceptance criteria
* On `/swap`
* After selecting the two assets and entering the amount
* On clicking swap, the swap transaction should be executed. 

## Technical considerations
* How to execute the swap transaction?

More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/110?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by gonzamontiel** [comment]
I have no access to https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8, so I cannot estimate properly.

**Comment by ebma** [comment]
## Technical refinement

> Swapping tokens for an exact number of output tokens is not implemented as of now. You always need to provide a minimum output amount that you expect and a deadline (Unix timestamp) after which the swap shall not be executed anymore. 


We need to call the '[swapExactTokensForTokens()](https://github.com/0xamberhq/contracts/blob/8fcc4f27cf3e83df3eec84115b14c0bfa1949566/contracts/src/core/Router.sol#L85)' function on the router contract. 

When calling that function we need to pass:
     * @param _amountIn     The amount of input tokens to swap
     * @param _amountOutMin The minimum amount that the user will accept
     * @param _tokenInOut   Array of size two, indicating the in and out token
     * @param _to           The recipient of the output tokens
     * @param _deadline     Unix timestamp after which the transaction will revert

Note: For this call to work, the user needs to grant the Router contract a sufficient allowance beforehand, by calling the `approve` function on the token contract that he wants to send assets from, specifying the address of the router contract as the allowed spender.

**Comment by nejcm** [comment]
So I implemented most of this functionality already for nabla/amber on the polygon/eth side. So We can probably reuse a lot of code just swap the calls.
