### ISSUE TITLE
Fetch wallet token balances for Nabla swap

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#111]
As a 0xAmber user, i should be able to see my token balances in the swap token dropdown

## Acceptance criteria
* On `/swap`.
* On clicking on the token dropdown.
* Show the amount for each token in the dropdown list the user holds in the wallet.

## Technical considerations
* How to fetch the tokens balances from the wallet?

More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/111?planning-poker) with Zenhub @ebma

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/111?planning-poker) with Zenhub @gonzamontiel

**Comment by gonzamontiel** [comment]
I don't have access to https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by nejcm** [comment]
Give me your emails: @gonzamontiel @ebma

**Comment by ebma** [comment]
## Technical refinement

We can fetch the balance of each token by calling the `balanceOf(address user)` function on each token contract with the user's address. We can assume that the token contracts are our ERC20-wrapper contracts. This function will communicate with our chain-extension to fetch the balance from chain, see [here](https://github.com/pendulum-chain/pendulum-ink-wrapper/blob/db10871f6ec81d74e0afe9e1e49b8f2e143aadc5/erc20-wrapper/erc20-wrapper.sol#L59).
