### ISSUE TITLE
Fetch user pool liquidity info for Nabla swap pools

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#115]
Deposit amounts, ...

More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment]
@nejcm all details wrt to pool are fetched in the ticket https://github.com/pendulum-chain/portal/issues/114 is there anything else apart from that we need to fetch? If not we can close this ticket wdyt?

**Comment by TorstenStueber** [comment]
@prayagd @nejcm can you clarify how or if this is required?

**Comment by prayagd** [comment]
@TorstenStueber In my understanding user pool liquidity info which i assume is the Amount that he has deposited in the pool. which we are already planning to fetch that detail in the #114 ticket. 
@nejcm let me know if i am missing anything with respect to this ticket.

**Comment by TorstenStueber** [comment]
Why do we need to assume here? Don't we come up with these requirement and therefore we are the ones to be able to precisely define this?

**Comment by nejcm** [comment]
As mentioned in the other ticket the requirements for this were takes from design. I guess for the overview (table) the user deposited pool amount is something most apps show and would be useful.

**Comment by TorstenStueber** [comment]
Thanks!

**Comment by prayagd** [comment]
closing as this is a older ticket
