### ISSUE TITLE
Add liquidity to Nabla swap pool

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#116]
As 0xAmber user, i should be able to add liquidity to the swap pools. 

## Acceptance criteria
* On `/swap-pools`
* Show table of pools
* On clicking `Deposit`
* Show pop-up for adding liquidity
* On this pop-up fetch these details
    * Wallet balance
    * Effective deposit*
    * Reward/penalty*
    * Total deposits*
    * Pool share - User share in the pool
* On confirming the deposit, the transaction to add liquidity in the 0xAmber swap pool should be executed. 

## Technical consideration
* How to fetch the above info?
* How to execute the transaction to add liquidity to swap pools. 

More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/116?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by prayagd** [comment]
@nejcm Also splitting this ticket to add and remove liquidity https://github.com/pendulum-chain/portal/issues/142

**Comment by TorstenStueber** [comment]
## Technical refinement

For the actual addition of liquidity: to add liquidity call the method `deposit` of the swap pool contract and specify the amount.

**Comment by prayagd** [comment]
@TorstenStueber 
* Wallet balance - The amount of tokens that user holds in their wallet. 
Regarding the other two have followed up with Andy.

**Comment by TorstenStueber** [comment]
Is this a requirement from the Nabla team? If we don't consider it a necessity to display values we can't precisely define, then I propose that we cut it.

**Comment by nejcm** [comment]
So the info mentioned above is living on the add liquidity screen in different parts. Wallet balance and deposit should be easy. They are fetched from the wallet and contract. Once the PR with balanceOf implementation is merged this should be very easy to get. Also the implementation can be seen in the nabla repo.
For reward we need more input from others
