### ISSUE TITLE
Fetch backstop pool and info for Nabla 

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#117]
More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment]
@nejcm There is no info apart from getting the user liquidity for the backstop pool for that there is already this ticket https://github.com/pendulum-chain/portal/issues/118 or am i missing anything?

**Comment by nejcm** [comment]
> @nejcm There is no info apart from getting the user liquidity for the backstop pool for that there is already this ticket #118 or am i missing anything?

Not sure if these will be separate methods or it can be fetched in one query as we need to fetch all pools and than user liquidity  for his pools

**Comment by TorstenStueber** [comment]
@prayagd @nejcm 

What are backstop pools? Shouldn't there only be a single backstop pool? What information do we need?

**Comment by ebma** [comment]
I'm also a bit confused why so many things are mentioning multiple backstop pools now. The https://github.com/0xamberhq/contracts/blob/8fcc4f27cf3e83df3eec84115b14c0bfa1949566/OVERVIEW.md#L26-L27 still only mentions one backstop pool. But I assumed that this changed by now and we have to expect more than one backstop pool @nejcm @prayagd?

**Comment by nejcm** [comment]
From my understanding there can be more than one even if at the start there will be only one. Will confirm with others

**Comment by prayagd** [comment]
@TorstenStueber @ebma There is only one backstop pool fixed the title and will also fix other titles.

**Comment by ebma** [comment]
If there would only be one, why can the UI show multiple @prayagd?

**Comment by prayagd** [comment]
@ebma https://github.com/pendulum-chain/portal/issues/183

**Comment by ebma** [comment]
Ah okay, so we will change the UI to just one pool, thanks.

**Comment by TorstenStueber** [comment]
Thanks for clarifying @prayagd, however, this ticket still lacks any detail. We can't work on it without a proper description.
