### ISSUE TITLE
Add liquidity to Nabla backstop pool

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#119]
As a Nabla user, I should be able to add liquidity to the Nabla backstop pool. 

## Acceptance criteria
* On `/backstop-pools`
* Show `Add liquidity` option for the pool
* On clicking it, show pop-up to enter the amount. 
* On confirm, the transaction to add liquidity should be executed. 

## Technical consideration
*  How to execute the transaction to add liquidity to the backstop pool?

More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/119?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by prayagd** [comment]
@nejcm breaking this into two tickets. Will keep this one for just adding and this for removing https://github.com/pendulum-chain/portal/issues/141.

**Comment by TorstenStueber** [comment]
## Technical refinement

To add liquidity call the method `deposit` of the backstop pool contract and specify the amount.
