### ISSUE TITLE
Show memo on the pending request. 

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#123]
As a spacewalk user, i should be able to see the memo text of the pending issue request. 

# Acceptance criteria
* On `/spacewalk/transfers`
* On Clicking pending request for `to Amplitude` or `to Pendulum`
* Show memo text in the pop-up.
* Currently the memo text is missing.

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/123?planning-poker) with Zenhub @gonzamontiel

**Comment by gonzamontiel** [comment]
Would this be needed only in Pending transactions? The transaction information box is reused in every status, so it might be cool if we actually show it always and not based on the status. does it makes sense?

**Comment by prayagd** [comment]
@gonzamontiel According to me the memo is more useful in the pending txn while bridging to Amplitude/Pendulum because in case the user closes the pop-up while bridging he has no way to find out the memo. While memo text in other status wont be that useful.
