### ISSUE TITLE
Amplitude dialogs text color change

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/portal#129]
Change low contrast white color over green.
![Screenshot from 2023-05-03 15 11 35](https://user-images.githubusercontent.com/4713407/235926601-0798aeb6-07a2-48cc-964f-5cfd677f000e.png)
To darker color over green on Amplitude.

![Screenshot from 2023-05-03 15 11 30](https://user-images.githubusercontent.com/4713407/235926593-3992aded-d10f-4064-b4b6-d8d0ef7c25a4.png)

Is barely visible and kinda hurts :v:

**Comment by gonzamontiel** [comment]
@prayagd thoughts?

**Comment by prayagd** [comment]
@gonzamontiel LGTM but does this colour fit our branding and do we uniformity across the Amplitude version?

**Comment by gonzamontiel** [comment]
hey, so I thought it as a proposal (it's not a PR), needs to be checked with Marin I guess.

**Comment by prayagd** [comment]
@gonzamontiel Let me get Klaus and Marina's feedback on this and get back.

**Comment by gonzamontiel** [comment]
what I understand from your comment @prayagd :

![Screenshot from 2023-06-01 18.40.35.png](https://images.zenhubusercontent.com/641c292481872ea4d8db8e72/7aa3de7b-7918-408c-a910-0c6c659742e7)

do you think is correct?

**Comment by prayagd** [comment]
@gonzamontiel Yes, this looks correct. The containers stand out now and also the text is better readable than the white one.
