### ISSUE TITLE
Add support for XLM/Stellar native vaults

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#136]
### Describe the bug
The pop-up for issuing XLM on amplitude is incomplete with missing details as memo, vault address and countdown timer. 

### Reproduction

1. Go to https://portal.pendulumchain.org/amplitude/spacewalk/bridge
2. Click on "To Amplitude"
3. Select XLM as currency and enter the amount and click "Bridge"
4. The pop-up shows up incomplete

### Expected behavior

* The pop-up must have 
    * address to send XLM
    * Issued by (vault address)
    * text memo
    * countdown timer
* The warning messaged should have XLM instead of USDC. 

### Screenshots

![image](https://user-images.githubusercontent.com/52105313/236818448-4cd1cc17-fbda-4d0a-b6e3-b6c6363da1b8.png)

**Comment by prayagd** [comment]
cc @gonzamontiel

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/136?planning-poker) with Zenhub @gonzamontiel

**Comment by gonzamontiel** [comment]
The warning message doesn't make sense for XLM. XLM has no issuer @prayagd

**Comment by prayagd** [comment]
@gonzamontiel you are right, we can remove this warning message.
