### ISSUE TITLE
Fix Dapp, Runtime and Network

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#144]
Currently the DApp, Runtime and Network are confusing to the enduser. We are not aware what information is fetched here. So writing this ticket to make minor fixes. 

## Requirement
* Remove Dapp
* Keep Runtime
* Change Network to Block no.

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/144?planning-poker) with Zenhub @gonzamontiel

**Comment by prayagd** [comment]
@gonzamontiel Hope this is clear now.

**Comment by gonzamontiel** [comment]
So, updating on this: 
**DApp** shows the result of `api.rpc.system.name()`
**Runtime** shows the result of `api.rpc.system.version()`

Lets use this ticket to define what to show to the user and under which label.

**Comment by erasmus** [comment]
We want to show to the end-user:

* The last block (for liveness check/reference)
* The current runtime version (for easy auditing -- they should be able to find the runtime version code on Github)
* The current version of the Portal app (a unique ID that references the deployed state, for example, commit hash)

I think the first two are easy to include, while the third may require more work, and so could be moved to a separate Github issue.

**Comment by prayagd** [comment]
@gonzamontiel Do you agree to @erasmus suggestion here? Then will remove the third one and create a new one. So we can progress on this ticket.

**Comment by gonzamontiel** [comment]
I agree with the described points. Also, for the third one, this is a value that we would like to generate, right? I don't know if that already exists. We have a tag system in CI that should increment the version inside package.json, but idk if this would be enough.
We can go ahead and redefine this ticket with the first two points.

**Comment by prayagd** [comment]
@gonzamontiel I have made the changes to the main description of this ticket. Regarding the Current version, we are now planning to have releases for the Portal and have release notes. On how to name them, lets sync on this in the weekly sync.
