### ISSUE TITLE
Show connected account's token-wise breakdown on the dashboard

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#145]
As a portal user, i should be able to see the token balances of all assets in the wallet (Native, XCM and Stellar) on Pendulum, Amplitude and Foucoco

## Acceptance criteria
* On `/Dashboard`
* Show a table of assets with four columns
* Column names - Token, Price, Amount, USD Value
* Total of all these tokens should be shown on top of table
* Please add pagination if the number of tokens dont fit in a single view
* Filters should be applicable here, the way they work on the collator table

## Terms
* Token - Token ticker
* Price - Price of the token
* Amount - Total number of tokens in the wallet
* USD value - Price * Amount

## Notes
* This ticket is just for the desktop version, will create separate one for mobile.
* Price's of stellar tokens can be fetched from DIA oracle 
    * USDC.s - https://www.diadata.org/app/price/asset/Ethereum/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/
    * XLM.s - https://www.diadata.org/app/price/asset/Stellar/0x0000000000000000000000000000000000000000/
    * TZS.s - https://api.diadata.org/v1/foreignQuotation/YahooFinance/TZS-USD
    * BRL.s - https://api.diadata.org/v1/foreignQuotation/YahooFinance/BRL-USD
* The above tokens should be only visible on Amplitude network as Spacewalk is live only on Amplitude
* Price's of XCM tokens from DIA oracle.
    * On Amplitude
    * KSM - https://www.diadata.org/app/price/asset/Kusama/0x0000000000000000000000000000000000000000/
    * USDT - https://www.diadata.org/app/price/asset/Ethereum/0xdAC17F958D2ee523a2206206994597C13D831ec7/
    * On Pendulum
    * DOT - https://www.diadata.org/app/price/asset/Polkadot/0x0000000000000000000000000000000000000000/
    * USDT -  https://www.diadata.org/app/price/asset/Ethereum/0xdAC17F958D2ee523a2206206994597C13D831ec7/
 * For native token prices
     * AMPE - AMPE token does not have price, so we can skip the price and the USD value column for it (Only on Amplitude)
     * PEN - https://www.mexc.com/exchange/PENDULUM_USDT?_from=market (Only on Pendulum)
     * AMPE(Foucoco) - Does not have a price
 * Tokens list
     * Pendulum - PEN, DOT, USDT
     * Amplitude - AMPE, KSM, USDT, USDC.s, BRL.s, TZS.s, XLM.s
     * Foucoco - AMPE 

## Technical considerations
* Non-native tokens i.e XCM are implemented using ORML-tokens pallet, with CurrencyId enum, called XCM(index) and the index contained in that type indicates which asset we are facing.
* Pendulum:
DOT at {XCM: 0}
USDT at {XCM: 1}
* Amplitude:
KSM at {XCM: 0}
USDT at {XCM: 1}

## Brand-assets
* Token icons - Will share these, but hope we can get started. 

## Wireframe
* https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=0-1&mode=design

**Comment by prayagd** [comment]
@gonzamontiel Will get you the design for this.

**Comment by prayagd** [comment]
@gonzamontiel This ticket is for the same. We are creating a design to show all the assests a wallet holds on the dashboard which includes spacewalk assets, XCM assets, and native assets. In this table we are planning to show Token name, Token amount, Token Price,  Total Amount(In USD). Do you think this makes sense? as we missing anything?

**Comment by gonzamontiel** [comment]
Hey @prayagd , I was saying that, besides showing them in the Dashboard, we can display the tokens also in the dropdown menu of the connected account (see screenshot). Or to also include the bridged ones in transfers/balances.
Here I speak about consistency.
For one side, we show a balance on the topbar, so we should show all balances, or like some wallets do, show the USD equivalent value of the total of the assets added up.
In the other hand, under Bridge or Spacewalk, we show a way to move tokens around, to see the list of transfers, but not user's bridged assets.
So in those two places we might want to show this info, besides the dashboard.

**Comment by prayagd** [comment]
@gonzamontiel I have updated the wireframe. Regarding your last comment lets discuss this in the sync i am not able to get you.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/145?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by gonzamontiel** [comment]
> Hey @prayagd , I was saying that, besides showing them in the Dashboard, we can display the tokens also in the dropdown menu of the connected account (see screenshot). Or to also include the bridged ones in transfers/balances. Here I speak about consistency. For one side, we show a balance on the topbar, so we should show all balances, or like some wallets do, show the USD equivalent value of the total of the assets added up. In the other hand, under Bridge or Spacewalk, we show a way to move tokens around, to see the list of transfers, but not user's bridged assets. So in those two places we might want to show this info, besides the dashboard.

Hey, I'm starting with this feature and I can work on it, but this haven't been addressed. The account dropdown shows this info:

 ![Screenshot from 2023-08-16 18 05 30](https://github.com/pendulum-chain/portal/assets/4713407/4605397d-e895-4e7c-aa8c-183bbb8b9a94)

And what I was wondering is what to show there, now that we have multiple assets.

**Comment by prayagd** [comment]
@gonzamontiel Lets have only PEN there.

**Comment by gonzamontiel** [comment]
I will need the asset icons for this ticker :) cc @prayagd

**Comment by prayagd** [comment]
@gonzamontiel shared with you on slack. PEN and AMPE can be found here https://pendulumchain.org/brand-assets
