### ISSUE TITLE
Change foucoco logo

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#148]
## Context

On foucoco the text "Foucoco testnet" text is not aligned with the logo. 

## Acceptance criteria

1. On 'https://portal.pendulumchain.org/foucoco/dashboard'
2. The text below the Amplitude logo is not aligned
3. New set of logo structure is attached in the ticket. 

## Attachements

https://drive.google.com/open?id=1_YG6lejVGjEeXjBzKvfWiu5V_UZINkIW&usp=drive_fs

**Comment by gonzamontiel** [comment]
hey, is this in Review? I don't see a linked PR

**Comment by prayagd** [comment]
@gonzamontiel We can close this ticket. Nejc already fixed it in this https://github.com/pendulum-chain/portal/pull/198. He was not aware of our flow of linking issues and PR.
