### ISSUE TITLE
Limit unexpected characters in the spacewalk input field

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#149]
## Describe the bug

The spacewalk input field accepts `e` and `-` as inputs. 

### Reproduction

1. Go to https://portal.pendulumchain.org/foucoco/spacewalk/bridge
2. Click on input field
3. Enter `e` and `-`
4. User should not be able to enter these characters in the input field
5. This error is present on both Amplitude and Pendulum

### Expected behavior

As spacewalk user, I should be able to input only numbers and "." in the input field of both "to Pendulum" and "Back to stellar"

### Screenshots
<img width="596" alt="Screenshot 2023-05-16 at 1 11 47 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/5a18b35b-8b79-455f-b041-c63e4eb2c8a4">

**Comment by gonzamontiel** [comment]
Hey @prayagd, PR is ready, but worth mention that the input field already was of type number.
The fact you could input "-" and "e" is because you can formulate a number in scientific notation lke 1e-3
But I understand this is unlikely, and I removed the Minusn and "e" from being sjown.

**Comment by gonzamontiel** [comment]
Fixed on staging.
