### ISSUE TITLE
Portfolio border not visible on Amplitude

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#151]
### Describe the bug

The portfolio on component on dashboard has a border but it is not visible on the Amplitude network

### Reproduction

1. Go to 'https://portal.pendulumchain.org/amplitude/dashboard'
2. See portfolio the border is not visible on this component. 

### Expected behavior

The border of the portfolio component should be clearly visible. Can be Amplitude green. Colours can be found here https://pendulumchain.org/brand-assets#pendulum-brand-assets

### Screenshots
<img width="533" alt="Screenshot 2023-05-16 at 1 25 47 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/1166165a-ca5a-49ea-b5af-4d5649452681">

**Comment by gonzamontiel** [comment]
Sorry, is this a change on the design? If that is the case it is not a bug. Borders are never the accent color (check all Pendulum and Amplitude designs). Pls confirm with Marine.

**Comment by prayagd** [comment]
To be proceeded once feedback from Marina is recieved.

**Comment by prayagd** [comment]
closing this as this a older ticket
