### ISSUE TITLE
Redeem - Autofill with personal data

### ISSUE THREAD

**Issue by LeoFraq** [pendulum-chain/portal#163]
### Describe the bug

Filling in the Redeem form tries to autofill with personal credentials

### Reproduction

1. Go to Bridge
2. Click on Back To Stellar
3. Enter stellar address, having saved personal data may be prompted for input

### Expected behavior

The form does not autofill with this data

### Screenshots

![image.png](https://images.zenhubusercontent.com/640f1eb404b2a44433611a9f/22497552-3043-4414-ac92-66429e7c50a3)

**Comment by gonzamontiel** [comment]
Hi @LeoFraq , thanks for the report! very useful to make the portal functions better. I changed the type to 'enhancement' because autofill isn't necessarily expected, and wasn't defined before. But I think we can implement it with low effort.
