### ISSUE TITLE
Add Update / Increment rewards option for staking

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/portal#170]
@vadaynujra commented on [Fri May 26 2023](https://github.com/pendulum-chain/tasks/issues/69)

### Requirement / User Story
As a staker (delegator and collator) on Pendulum and Amplitude, I want to be able to increment / update my rewards so that I can claim it, on the portal.

![image.png](https://images.zenhubusercontent.com/640f0fdad0d880db9ecf5dae/77c8157e-ce59-4963-b9f3-7e83f561117f)
![image.png](https://images.zenhubusercontent.com/640f0fdad0d880db9ecf5dae/4037e26f-a71a-4b29-83d1-bf869b9a3a9f)

### Task
* Add button that calls the extrinsics incrementCollatorRewards() and incrementDelegatorRewards() first so that the rewards are updated
* Call extrinsic on wallet connect

Example from [Penguin.pe](https://penguin.pe/)
 
![image.png](https://images.zenhubusercontent.com/640f0fdad0d880db9ecf5dae/345c07b4-c57d-459b-8004-8f365df2125f)

---

@vadaynujra commented on [Fri May 26 2023](https://github.com/pendulum-chain/tasks/issues/69#issuecomment-1564473131)

Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/tasks/69?planning-poker) with Zenhub @ebma @gonzamontiel

---

@ebma commented on [Fri May 26 2023](https://github.com/pendulum-chain/tasks/issues/69#issuecomment-1564505229)

I checked and the extrinsics are limited as to who can call them. `incrementCollatorRewards()` can only be called from the account of a collator and `incrementDelegatorRewards()` can only be called from the account of a delegator. 

Thus, the button should actually only call the [incrementDelegatorRewards()](https://github.com/pendulum-chain/pendulum/blob/44f0d6d46da12810c4cef6b9df3d96620360dc5e/pallets/parachain-staking/src/lib.rs#L1763) extrinsic for the currently connected wallet account.
Alternatively we could also try to call both extrinsics when clicking on the button so that we cover both cases and collators as well as delegators can use this functionality to claim their rewards. But then we have to expect one of these extrinsic calls to fail and handle that accordingly.

---

@ebma commented on [Tue May 30 2023](https://github.com/pendulum-chain/tasks/issues/69#issuecomment-1568448744)

Why is this ticket not in the portal repo though @vadaynujra?

---

@gonzamontiel commented on [Tue May 30 2023](https://github.com/pendulum-chain/tasks/issues/69#issuecomment-1568467288)

Hu, I came here to say the same, because I haven't found it on ZenHub and figured out it was mistakenly added to another repo. Is there an easy way to move, I noticed this repo is private, and I cannot move it to a public one :/?

---

@ebma commented on [Tue May 30 2023](https://github.com/pendulum-chain/tasks/issues/69#issuecomment-1568469684)

Yeah there's an option to transfer the issue but I'd like to have @vadaynujra clarify first whether there is a reason for the ticket to live here.

---

@ebma commented on [Tue May 30 2023](https://github.com/pendulum-chain/tasks/issues/69#issuecomment-1568470472)

Oh lol, you're right we can't move it because it's private @gonzamontiel. That's interesting

---

@vadaynujra commented on [Tue May 30 2023](https://github.com/pendulum-chain/tasks/issues/69#issuecomment-1568507896)

@ebma no reason to have added it here. Should be in the portal. Can it be moved?

---

@vadaynujra commented on [Tue May 30 2023](https://github.com/pendulum-chain/tasks/issues/69#issuecomment-1568510041)

Please new create a ticket for the portal and close this @ebma @gonzamontiel ?

**Comment by ebma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/170?planning-poker) with Zenhub @gonzamontiel

**Comment by vadaynujra** [comment]
@prayagd who is expected to review this one?

**Comment by prayagd** [comment]
@vadaynujra It is already reviewed by Marcel, waiting for Gonza to reply on the comments. https://github.com/pendulum-chain/portal/pull/181#pullrequestreview-1470190135
