### ISSUE TITLE
Only show transfers for connected account

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/portal#177]
### Observation
Currently all users can view all bridge requests under the Transfers tab.

![image.png](https://images.zenhubusercontent.com/640f0fdad0d880db9ecf5dae/ac4d9e90-7f06-4791-9473-3c6ebad5b81f)

### Requirement
Only transfers from the connected accounts should be displayed.
When no account is connected, no transfers are displayed.

**Comment by gonzamontiel** [comment]
My 2 cents here. I think that at this point of usage it would be nice to show a large amount of transfers, the users know the bridge is being "largely" used.
We can instead add a filter like "Show only mine", and maybe make it the default. Or the other way around, only show user's transfer but with a "Show all". I'm interested in your thoughts @adelarja @prayagd

**Comment by prayagd** [comment]
@gonzamontiel That is good point to signal to users that the bridge is largely used but when thinking UX wise it would be better to show only the txn the user has done no? What if we add a filter and keep it default as "Show only mine" with option to change to "Show all". That was anyone interested in seeing what other txns are can do. 
I am more interested in knowing the efforts here
1. What are the efforts to add a filter?
2. What are the efforts to make it permanently to show only user txn?

**Comment by vadaynujra** [comment]
As a DeFi / bridge user I actually found it quite confusing to see a list of transactions with different statuses when I hadn't even made a transaction, probably because most protocols only display transactions I have made. I know a few more users who shared the same feeling. 
On the other hand, I didn't really find it impressive to see >50 transactions on Spacewalk or even be able to contexualise if this was a positive indicator. So in summary:
Confusion - 1
Impressiveness - 0

**Comment by gonzamontiel** [comment]
> @gonzamontiel That is good point to signal to users that the bridge is largely used but when thinking UX wise it would be better to show only the txn the user has done no? What if we add a filter and keep it default as "Show only mine" with option to change to "Show all". That was anyone interested in seeing what other txns are can do. I am more interested in knowing the efforts here
> 
> 1. What are the efforts to add a filter?

I think I would give 3 to 5 story points to that.

> 2. What are the efforts to make it permanently to show only user txn?

I would give it 3 story points, considering that we need a placeholder for when there are no transfers, to be consistent with the UX


Regarding @vadaynujra stats:
> Confusion - 1
> Impressiveness - 0

Haha okay, looks to me a bit biased but if it is the feedback that we have, we can go ahead and only show user's transfers. Please add the placeholder/text you want to show when there's no transfer yet.

**Comment by gonzamontiel** [comment]
Also, @prayagd and @vadaynujra, take into account that we don't have any other place where to see this summarized info. I'm thinking mostly in dev/product with testing purposes, but also to troubleshoot someone else's transfers. At least for me, it would make sense to have access to all transfers.

**Comment by vadaynujra** [comment]
@gonzamontiel the transactions view in the portal is not for us to use for troubleshooting and I expect the tech team to be able to use Polkadot.js for that? So we should only be thinking from a user perspective. It's also the laser sharp view that we are trying to get company-wide. Please elaborate on the bias you see in the feedback shared above? Just because it seems basic to me, doesn't mean it should be necessarily implemented.

**Comment by gonzamontiel** [comment]
hey @vadaynujra , 

> @gonzamontiel the transactions view in the portal is not for us to use for troubleshooting and I expect the tech team to be able to use Polkadot.js for that?
Nope, this is not the case, as I said before, we cannot use PolkadotJs for that.

I don't mind implementing this feature as you wish. Agree that we cannot think of a product based on the testing purposes, my point of view was strictly tied to the fact we are in an early stage of the product.
For testing purposes, if needed, we can remove the filter in the branch we are testing, etc.

**Comment by gonzamontiel** [comment]
Hey @prayagd please provide a default placeholder/behavior when no account is connected, so we can complete the feature request and implement it.

**Comment by prayagd** [comment]
@gonzamontiel The default behaviour should be this https://portal.pendulumchain.org/pendulum/spacewalk/transfers

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/177?planning-poker) with Zenhub @ebma @gonzamontiel
