### ISSUE TITLE
Rename Collators to Staking in navigation menu

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#179]
As a portal user, i should see Staking in the navigation menu

## Acceptance criteria
* Rename the `Collator` item to `Staking`

**Comment by prayagd** [comment]
@nejcm Can you please push this change to staging.

**Comment by vadaynujra** [comment]
@prayagd has this already completed? If not, what's the blocker in pushing it to staging?

**Comment by prayagd** [comment]
@vadaynujra No blocker as such, it got lost in the priorities from last couple of weeks.
