### ISSUE TITLE
Show staking rate

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#180]
As a portal user, i should see the staking rate for Pendulum/Amplitude

## Acceptance criteria
* Show the staking rate for the network in %

## Notes
* How to find staking rate?
* Total PEN staked / Total issuance
* Total issuance can be fetched here - https://api.pendulumchain.tech/v1/amplitude/token/stats
* Total PEN staked - Add up all the values from collators.

**Comment by prayagd** [comment]
@gonzamontiel Can the staking rate be calculated by the method shown above? on where to show it we havent decided yet but will get you the designs.

**Comment by prayagd** [comment]
@gonzamontiel Can you please confirm?

**Comment by gonzamontiel** [comment]
Okay I understand this calculation is good enough, but rather simple. What do you want to achieve with this info? A better indicator would be the APR, as explained [here](https://medium.com/cosmostation/staking-apr-how-is-it-calculated-466f5091dfd2).
Besides, the ticket is incomplete as it doesn't say where to show this value.

**Comment by prayagd** [comment]
Closing as this a older ticket and not a requirement as of now
