### ISSUE TITLE
Integrate WalletConnect

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#182]
As a portal user, i should be able to connect to the portal using WalletConnect

## Acceptance criteria
* Integrate wallet connect in portal
* Steps for integration are shown here https://docs.walletconnect.com/2.0/web3modal/polkadot/dapp-integration-guide

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/182?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by prayagd** [comment]
This ticket is just for the code integration, Will create a separate ticket for the UI. Can you please add your estimates?

**Comment by vadaynujra** [comment]
Updated priority to `high`. 
This is an opportunity to be the first movers to support WalletConnect in the ecosystem, from a dApp perspective. Alex believes it would be a big win to announce at decoded, at the end of the month.

**Comment by ebma** [comment]
This can be considered completed by #195.
