### ISSUE TITLE
Backstop pool for 0xAmber

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#183]
As a 0xAmber user, i should be able to deposit and withdraw assets from the backstop pool

## Acceptance criteria
* On /backstop-pool
* Show two options Add liquidity and Withdraw along with pool balance

Note
* Nothing else needs to be changed the Add and Withdraw pop-ups work. 
* Current screen
* <img width="1148" alt="Screenshot 2023-06-22 at 6 10 21 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/5fe94ff5-27f6-47f1-82a1-17d4d9f269b0">
* Expected screen
* <img width="667" alt="Screenshot 2023-06-22 at 6 11 11 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/b36e3af5-7a61-4338-b753-2ee66da1da56">

## Design
https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=1109-3549&t=MfomBcbnoyBCwuLr-4

**Comment by TorstenStueber** [comment]
@prayagd Is this ticket also relevant for @ebma and me? Or is there still UI work required?

**Comment by prayagd** [comment]
@TorstenStueber This is the UI work required and have asked @nejcm to look at it.

**Comment by nejcm** [comment]
So, some comments here. From my understanding while at the start there might be only one backstop pool in the future there might be more, so we also need an overview screen like the table view for swap pools. That's why my initial ui looks different from the figma design.

**Comment by prayagd** [comment]
@nejcm Ok, Currently there is only one backstop pool and we are not sure when the new backstop pools would come in picture. IMHO we should only have the UI for one backstop pool instead of placeholders for more.

**Comment by TorstenStueber** [comment]
I agree. Keep it as simple as possible and only add complexity when we really need it.
Possibly YAGNI
