### ISSUE TITLE
Integrate on-ramp on the portal.

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#188]
As portal user, i should be able to buy PEN from the portal

## Acceptance criteria
* Show `Buy PEN` on the navigation menu
* On `\buy` do a page integration of the on-ramp UI
* Details to a page integration - https://alchemypay.readme.io/docs/page-integration-2 
* Integration approach should be redirection
* This option should only be available on the Pendulum version of Portal

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/188?planning-poker) with Zenhub @ebma @nejcm

**Comment by ebma** [comment]
@prayagd can you clarify which of the two approaches mentioned [here](https://alchemypay.readme.io/docs/page-integration-2) you'd like to have? Redirection or iframe?

**Comment by prayagd** [comment]
@ebma What would be the least effort among them?

**Comment by ebma** [comment]
I think 'Redirection' would be easier and less error-prone. For the iframe, we'd have to worry about screen sizing etc.

**Comment by prayagd** [comment]
@ebma Thanks, updated in the main description.

**Comment by gonzamontiel** [comment]
Just to be clear, the Nav item won't redirect to /buy but it will be a link as provided in their docs, like this:

```
<a href="https://ramptest.alchemypay.org/?appId=[YOUR_TEST_APPID]&[QUERY_PARAMETERS]>">
Buy/Sell Crypto with AlchemyPay</a> 
```

**Comment by gonzamontiel** [comment]
Also, all items in the Navigation menu have an icon. What should I use here @prayagd  ?

**Comment by gonzamontiel** [comment]
the issue is blocked until we've got the corresponding tokens (and the icon)

**Comment by prayagd** [comment]
@gonzamontiel the icon and the production keys are shared with you on the portal channel, Please let me know if you need anything else.
