### ISSUE TITLE
Buttons on the Portal do not convey proper UX

### ISSUE THREAD

**Issue by LeoFraq** [pendulum-chain/portal#207]
### Describe the bug

The tabs at the side of the portal do not convey the existence of dropdown menu's correctly

### Reproduction

1. Go to The Portal https://portal.pendulumchain.org/amplitude/dashboard
2. Click on Amplitude
3. Compare the Dashboard button (Indicates an arrow to the side, has no dropdown) with the Spacewalk button (no arrow to the side, has dropdown)

### Expected behavior

Only the menu items with sub-items would have arrows. All others can be removed.
Menu items with Arrows

Spacewalk
Nabla

### Screenshots

![Screenshot 2023-07-05 at 16.49.28.png](https://images.zenhubusercontent.com/640f1eb404b2a44433611a9f/e1984c72-6f10-419e-a7f1-1efbda3a5a8f)
### Desktop (please complete the following information):

- Browser: Chrome

**Comment by ebma** [comment]
So what's the expected action here? Removing the arrow altogether?

**Comment by LeoFraq** [comment]
Remove the arrow icon from the dashboard button, include the arrow icon on Spacewalk, have it act as a proper dropdown and not a direct link OR remove it for both

**Comment by ebma** [comment]
Okay. Can you decide on one of these two approaches with @prayagd and mention the approach you agree on in the description of the ticket?

**Comment by prayagd** [comment]
@ebma I would put this on hold as i haved asked Marina to get the designs for it, So we stay consistent throughout the instead of making a choice of approach here.

**Comment by prayagd** [comment]
So got the feedback, only the menu items with sub-items would have arrows. All others can be removed.
Menu items with Arrows
* Spacewalk 
* Nabla
 cc @gonzamontiel

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/207?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by gonzamontiel** [comment]
Hey, I checked the designs and there is no consistency there. To summarize:
- Selected items will only be highlighted, no arrow to the tight side, like the example below:
![Screenshot from 2023-11-24 11 58 17](https://github.com/pendulum-chain/portal/assets/4713407/acce527e-3cc0-4ee4-931d-3116b74dca81)

- Dropdown items will have the default behavior app-wise for dropdowns, example below (from the Dropdown component):
![Screenshot from 2023-11-24 11 56 04](https://github.com/pendulum-chain/portal/assets/4713407/9708a04a-3df9-4705-a6c3-7f839571295b)
![Screenshot from 2023-11-24 11 56 08](https://github.com/pendulum-chain/portal/assets/4713407/1d2000a9-a74f-450a-9a19-a0f435fb280d)

Please confirm  @prayagd

**Comment by prayagd** [comment]
@gonzamontiel yes i confirm this and would make all the designs consistent
