### ISSUE TITLE
Connect Portal to Foucoco (testnet)

### ISSUE THREAD

**Issue by erasmus** [pendulum-chain/portal#21]
As a developer/tester, I'd like to connect to Foucoco, the Rococo testnet version of Amplitude/Pendulum, so I can try out new features in a safe way.

* On route `portal.pendulumchain.org/foucoco/`, connect to the Foucoco 
* Following endpoints are available: 

| hostname | FQDN | Function |
| --- | --- | --- |
| penrpc-roc-00 | rpc-foucoco.pendulumchain.tech | Foucoco RPC Node |

**Comment by erasmus** [comment]
@gonzamontiel  are the above endpoints correct?

**Comment by gonzamontiel** [comment]
> @gonzamontiel are the above endpoints correct?

They are correct in terms of naming, but those nodes aren't up yet, so not suitable for sharing. We published 4 collator nodes so far and they are:
`pencol-roc-00`, `pencol-roc-01`, `pencol-roc-02` and `pencol-roc-03`.
I say we share those for the time being.

**Comment by prayagd** [comment]
@nicolasdanelon We have new RPC endpoint for foucoco rpc-foucoco.pendulumchain.tech 
@gonzamontiel can the foucoco archive nodes can also be accessed by this rpc?

**Comment by gonzamontiel** [comment]
> @gonzamontiel the foucoco archive nodes can also be accessed by this rpc?

We can only test that if Zoltan includes the Archive as a possible target under the Load Balancer.  But tbh, I don't think it will work automagically. We would need to have some logic in place, so when someone queries a block that is too in the past (like, more than a normal collator saves), it redirects the request to the archive. Unfortunately, this is a bit complex to do.

**Comment by prayagd** [comment]
@gonzamontiel Thanks for the explanation. @erasmus any specific reason why we want the archive node connected? Can we skip this for this first version and just connect the RPC?

**Comment by erasmus** [comment]
> @gonzamontiel Thanks for the explanation. @erasmus any specific reason why we want the archive node connected? Can we skip this for this first version and just connect the RPC?

No, I sourced those endpoint from some internal docs. We only need the RPC one (indexer will come in the future for the historic data)

**Comment by prayagd** [comment]
@nicolasdanelon This is ready for development.

**Comment by prayagd** [comment]
Moving this to done as the portal is connected to foucoco.

**Comment by erasmus** [comment]
@prayagd this is still open? Should we close?

**Comment by prayagd** [comment]
This is closed. It is now connected to foucoco.
