### ISSUE TITLE
Show my staked token collator first on the collator table.

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#219]
As a portal user, i should be able to see the collator that i have delegated tokens on the first page as first line item. 

## Acceptance criteria
* On `/Collators`
* If user has staked tokens to any of the collator
* For ex. If i have staked to Polkadotters, then Polkadotters should be visible as the first line item on the collator table
* Example of the above statement is show below in the screenshot
* Currently the user has to navigate to find the collator they have staked to.

## Note
* Polkadotters is the name of the collator.

## Expected behaviour
<img width="1138" alt="Screenshot 2023-08-04 at 3 16 41 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/45373b6a-f5b9-41f5-a0f5-6a8fb7837239">

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/219?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by gonzamontiel** [comment]
Question, is this as simple as sort by 'My Staked' ? Or the collator should be fixed no matter which sorting is he using ?

**Comment by prayagd** [comment]
If I have staked my tokens and I connect my wallet, by default the collator
that I have staked on should appear first in the list on the first page.

**Comment by gonzamontiel** [comment]
I know, I know. Let me explain:

Since users can only stake to one collator, then ordering by 'My Stake' will bring your collator up, and thus, accomplish what you ask.
Another way of doing it is to fix that collator besides the sorting. i.e., your collator is shown first no matter if you sort by name, total staked, or whatever. I am asking which approach do you expect.

**Comment by prayagd** [comment]
ah ok, then First one.
