### ISSUE TITLE
Show list of collators

### ISSUE THREAD

**Issue by erasmus** [pendulum-chain/portal#22]
As $AMPE holder, I want to see the list of collators that are active on the network.

# Acceptance criteria

## Collator dashboard
* On `/collators`
    * In a container show available AMPE balance
* Show list of collators below the container with the details 
    * Collator name
    * Total staked
    * Delegators
    * APY
    * Delegated amount
* Show `Delegate` button in front of each list item

## Terms used in the wireframe

* Available balance: User's `AMPEBalance` 
* Total staked: `Amount of tokens that are locked on that collator`
* Delegated: `Amount of tokens staked by the user on that specific collator`
* Delegators: `Number of delegators that have delegated to that collator`
* APY: `% of rewards the user would get for his delegated amount`

### Notes

* All data is read only. Except buttons and input field. Which are explicitly mentioned. 
* Attaching Low fidelity wireframes for more context. 

### Wireframe
https://www.figma.com/file/XLIKffEYnK9autHMM1YgA3/Flows?node-id=0%3A1&t=rDjECzvp3Y8Zm7gV-0

# Technical considerations
* data to fetch from the chain
   * the list of collators
     * returned by `api.query.parachainStaking.candidatePool.entries()`
     * this returns an array (the list of collators), where every member has is an array with two entries of the form `[key, value]`
     * the `key` contains the address of the collator, extract it using `key.args[0].toHuman()`
     * the `value` contains the remaining information, extract it using `value.unwrap()`, this returns an object with the members
        * `total`: this is the total staking amount of the collator, display in column "Total staked" (see below for how to display amounts)
        * `delegators`: an array containing information about the delegators for this collator, you only need to get the length of this array to display the number of delegators
        * each member of the `delegators` array contains an entry `owner` and `amount`
           * if there is an `owner` entry that is equal to the account of the user, then display the `amount` in the "Delegated" column (see below for how to display amounts)
   * the APY
     * is the same for every collator and only needs to be queried once
     * returned by `api.query.parachainStaking.inflationConfig()`
     * this returns an object `info`, the APY is then `info.collator.rewardRate.annual.toHuman()`
* all amounts are raw amounts (i.e., scaled by 1_000_000_000_000) and stored in a big number object 
   * **it is important not to convert this into a number directly as this will lead to data loss, instead it should be converted as `Number(amount.divn(1000000).divn(1000)) / 1000`**
   * this will create a number with three decimal precision
* Additional documentation wrt to pallet can be found here 
    * [Internal docs](https://www.notion.so/satoshipay/22-07-04-Parachain-Staking-2774927465be42cca1898a36817edb95)
    * Pallet code [documentation](https://github.com/pendulum-chain/pendulum/blob/main/pallets/parachain-staking/src/lib.rs)

**Comment by erasmus** [comment]
Questions:

* Which endpoint to use for posting data?
* Where to pull collator `Name`, `Total bonded`, `APY`, `Staked`?

**Comment by ebma** [comment]
> Which endpoint to use for posting data?

Just to clarify, this question is asking how and where would the web app send the info that some amount is to be delegated/undelegated?

**Comment by ebma** [comment]
So, the functionality for staking and delegation is exposed by the parachain staking pallet. Since we copied the one from KILT, the API is the same. A documentation of that functions in JS is [here](https://github.com/KILTprotocol/sdk-js/blob/b6fc55f58c884e75a89e4c741349e5b7064c091b/packages/augment-api/src/interfaces/augment-api-tx.ts#L1335) but they are also explained in the code [here](https://github.com/pendulum-chain/pendulum/blob/main/pallets/parachain-staking/src/lib.rs). 

This interface will again be exposed by polkadot.js. It can be used to call the extrinsics to delegate/undelegate and to pull the data that you are looking for.
For calling extrinsics you have to send transactions (explained [here](https://polkadot.js.org/docs/api/cookbook/tx)) and
the rest of the data should be available at the polkadot.js API object somewhere similar to `api.query.parachainStaking`.

**Comment by erasmus** [comment]
> Just to clarify, this question is asking how and where would the web app send the info that some amount is to be delegated/undelegated?

I believe so. @nicolasdanelon can you add more details?

**Comment by TorstenStueber** [comment]
@erasmus This ticket requires to
- Alter the blockchain state: this happens through extrinsic functions as @ebma pointed out. In addition to the links posted they are also explained [in our internal docs](https://www.notion.so/22-07-04-Parachain-Staking-2774927465be42cca1898a36817edb95).
- Read the blockchain state: this is the real problem. Without any additional tools (like Subsquid) we can't simply read the state that you want to display. The storage is [explained here](https://www.notion.so/satoshipay/22-07-04-Parachain-Staking-2774927465be42cca1898a36817edb95#c38302fd6ae249b4868d4b45d527ceb7) and that is the only state we can read directly. For example, it is not possible to display how many rewards an account already received.

**Comment by erasmus** [comment]
> * Read the blockchain state: this is the real problem. Without any additional tools (like Subsquid) we can't simply read the state that you want to display. The storage is [explained here](https://www.notion.so/satoshipay/22-07-04-Parachain-Staking-2774927465be42cca1898a36817edb95#c38302fd6ae249b4868d4b45d527ceb7) and that is the only state we can read directly. For example, it is not possible to display how many rewards an account already received.

Ok, so first version will have to be without the historic data. @prayagd could you please update the ticket accordingly?

**Comment by prayagd** [comment]
@ebma from the above we understood that rewards cant be fetched. I will update the wireframes accordingly. Can you also help confirming the other data points can be fetched or not?

- Name or address of the collator
- Total staked or delegated to that candidate
- Number of delegators to a candidate
- APY
- Amount staked by the delegator
- and minimum bond amount

**Comment by ebma** [comment]
I think most of this data is available from the 'Candidate' struct that can be fetched for every registered candidate from the 
[CandidatePool](https://github.com/pendulum-chain/pendulum/blob/2e9f64374eabc3a573d7b403352ff212a27f1ed2/pallets/parachain-staking/src/lib.rs#L556)
- Name or address of the collator
   - name is not available, but the [account ID](https://github.com/pendulum-chain/pendulum/blob/2e9f64374eabc3a573d7b403352ff212a27f1ed2/pallets/parachain-staking/src/types.rs#L112)
- Total staked or delegated to that candidate & Number of delegators to a candidate
   - Fetch the `CandidatePool` to get all collator candidates
   - Each 'candidate' struct  has info on the [own staked amount ](https://github.com/pendulum-chain/pendulum/blob/2e9f64374eabc3a573d7b403352ff212a27f1ed2/pallets/parachain-staking/src/types.rs#L115) and the stake [delegated to it](https://github.com/pendulum-chain/pendulum/blob/2e9f64374eabc3a573d7b403352ff212a27f1ed2/pallets/parachain-staking/src/types.rs#L118)
- APY
   - staking rates are exposed in rpc runtime [function](https://github.com/pendulum-chain/pendulum/blob/2e9f64374eabc3a573d7b403352ff212a27f1ed2/pallets/parachain-staking/src/runtime_api.rs#L40)   
- Amount staked by the delegator
    -  also contained on the candidate struct  see [here](https://github.com/pendulum-chain/pendulum/blob/2e9f64374eabc3a573d7b403352ff212a27f1ed2/pallets/parachain-staking/src/types.rs#L118)
- minimum bond amount
   - [MinDelegatorStake](https://github.com/pendulum-chain/pendulum/blob/2e9f64374eabc3a573d7b403352ff212a27f1ed2/pallets/parachain-staking/src/lib.rs#L272) (for becoming a delegator)  is a constant  that can be fetched

**Comment by prayagd** [comment]
@nicolasdanelon Please check and Let me know if you need anymore details for the ticket. Otherwise it is ready to develop.

**Comment by ebma** [comment]
All data is again exposed through the polkadot.js API. After initializing and connecting it to the target chain (Amplitude) you should be able to query all data as you did before, meaning that all queries should available at `api.query.parachainStaking`. Constants are available with `api.consts.parachainStaking` (see [this](https://polkadot.js.org/docs/substrate/constants) doc)

**Comment by prayagd** [comment]
@TorstenStueber Please share the javascript code explanation on how to fetch data.

**Comment by ebma** [comment]
With polkadot.js the basics for querying data is always the same. 

The relevant type definitions from KILT are [here](https://github.com/KILTprotocol/sdk-js/blob/24d03aac07a13feb437389b7e1b9636746b028a8/packages/augment-api/src/interfaces/augment-api-query.ts#L303) and [here](https://github.com/KILTprotocol/sdk-js/blob/e3a4e0dc4a81e6e2279adacd2cfc4309814c9c98/packages/augment-api/src/interfaces/augment-api-consts.ts#L223). 

These types should be exposed by the initialized polkadot.js API object in `query` and `const` respectively. It is explained in more detail [here](https://polkadot.js.org/docs/api/start/api.consts) and [here](https://polkadot.js.org/docs/api/start/api.query)

**Comment by prayagd** [comment]
@nicolasdanelon I have updated the javascript code on how to fetch data and consts in the **Technical considerations** above. @ebma @TorstenStueber Can you please help confirming can we fetch the number of delegators for a specific collator?

**Comment by nicolasdanelon** [comment]
@gonzamontiel the code is ready for review #32 🤓 ✨ 
cc @erasmus @prayagd

**Comment by prayagd** [comment]
@nicolasdanelon Added comments on the PR.

**Comment by prayagd** [comment]
@gonzamontiel I moved this ticket in the backlog. As you might have to update the UI first according to the new branding of the existing collator list. 🙏🏻

**Comment by gonzamontiel** [comment]
@prayagd can you detail what is missing from this ticket besides the UI? 
If funcionality-wise is done, can we close it and create another one for the rebranding?

Otherwise, please list what should be worked on.

**Comment by gonzamontiel** [comment]
Also @ebma, it this a good place to integrate the new API, if it's not yet integrated ?

**Comment by ebma** [comment]
What do you mean by the 'new API' @gonzamontiel? I think regarding this list of collators nothing changed in the meantime. 
Unfortunately, you will not profit from the '@pendulum-chain/types' package just yet because the metadata I used to generate the types was from Spacewalk's testchain (as it is the only chain that has all Spacewalk pallets right now) but that chain does not use the parachainStaking pallet. I'd have to regenerate the types once the Spacewalk pallets were successfully added to either Amplitude or Pendulum so that both the types for Spacewalk pallets and this staking pallet are available.

**Comment by prayagd** [comment]
@gonzamontiel The only functionality-wise thing missing is currently the APY is fetched for collators we want to it be fetched for the delegators. 

while i will create a new ticket for the branding update of the collator list UI.

**Comment by gonzamontiel** [comment]
> What do you mean by the 'new API' @gonzamontiel? I think regarding this list of collators nothing changed in the meantime. Unfortunately, you will not profit from the '@pendulum-chain/types' package just yet because the metadata I used to generate the types was from Spacewalk's testchain (as it is the only chain that has all Spacewalk pallets right now) but that chain does not use the parachainStaking pallet. I'd have to regenerate the types once the Spacewalk pallets were successfully added to either Amplitude or Pendulum so that both the types for Spacewalk pallets and this staking pallet are available.

I was referencing the '@pendulum-chain/types'  package, I had the understanding that it had some other helper functions and it worked as a wrapper of the polkadot api with more functionality, sorry if that was a misunderstanding.
Now it's clear that I don't need to integrate that to fetch the collator's info.

**Comment by gonzamontiel** [comment]
> @gonzamontiel The only functionality-wise thing missing is currently the APY is fetched for collators we want to it be fetched for the delegators.
> 
> while i will create a new ticket for the branding update of the collator list UI.

I didn't understand this message. Can you clarify? Delegation isn't handled in https://github.com/pendulum-chain/portal/issues/26 ?

Or you mean number of delegators per collator as in this message? 
> @nicolasdanelon I have updated the javascript code on how to fetch data and consts in the **Technical considerations** above. @ebma @TorstenStueber Can you please help confirming can we fetch the number of delegators for a specific collator?

**Comment by prayagd** [comment]
<img width="464" alt="Screenshot 2023-02-01 at 6 10 43 PM" src="https://user-images.githubusercontent.com/52105313/216045146-81a89863-0f46-4b29-b323-2645373d0d0d.png">

@gonzamontiel In the collator list we are showing certain parameters. See screenshot above(taken from the user story written above). Out of these parameters the fourth one APY is currently fetched wrong. See in the screenshot below Nicolas was provided wrong endpoint to fetch it for collators but as the collator list is for end users who are delegators. It makes sense to show what APY the delegators recieve instead of showing what collators recieve. We want to get the Delegators APY. Current displayed APY is wrong. I hope this is clear. Happy to provide more context if not clear. 

<img width="703" alt="Screenshot 2023-02-01 at 6 12 06 PM" src="https://user-images.githubusercontent.com/52105313/216045442-31d35fba-de31-4a45-bffb-6f0b65aa3d83.png">

**Comment by ebma** [comment]
> I was referencing the '@pendulum-chain/types' package, I had the understanding that it had some other helper functions and it worked as a wrapper of the polkadot api with more functionality, sorry if that was a misunderstanding.

That's not a wrong assumption at all, you are right about this. However, I think it does not really offer anything that would be helpful to you here yet. The types for the staking pallet would help but as I said these unfortunately are not available in that package. Sorry for that inconvenience.

**Comment by gonzamontiel** [comment]
> <img alt="Screenshot 2023-02-01 at 6 10 43 PM" width="464" src="https://user-images.githubusercontent.com/52105313/216045146-81a89863-0f46-4b29-b323-2645373d0d0d.png">
> 
> @gonzamontiel In the collator list we are showing certain parameters. See screenshot above(taken from the user story written above). Out of these parameters the fourth one APY is currently fetched wrong. See in the screenshot below Nicolas was provided wrong endpoint to fetch it for collators but as the collator list is for end users who are delegators. It makes sense to show what APY the delegators recieve instead of showing what collators recieve. We want to get the Delegators APY. Current displayed APY is wrong. I hope this is clear. Happy to provide more context if not clear.
> 
> <img alt="Screenshot 2023-02-01 at 6 12 06 PM" width="703" src="https://user-images.githubusercontent.com/52105313/216045442-31d35fba-de31-4a45-bffb-6f0b65aa3d83.png">

now that is more clear, thank you!

**Comment by gonzamontiel** [comment]
> > I was referencing the '@pendulum-chain/types' package, I had the understanding that it had some other helper functions and it worked as a wrapper of the polkadot api with more functionality, sorry if that was a misunderstanding.
> 
> That's not a wrong assumption at all, you are right about this. However, I think it does not really offer anything that would be helpful to you here yet. The types for the staking pallet would help but as I said these unfortunately are not available in that package. Sorry for that inconvenience.

I was asking because maybe we can include those helpers aswell in that package and leave the portal code cleaner. I wil give it a look.

**Comment by prayagd** [comment]
There is a update branding ticket for this #45. So closing this.
