### ISSUE TITLE
Update Spacewalk "To Pendulum" Design

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#221]
As a portal user, i should see new "To Pendulum design" for the Spacewalk bridge

## Acceptance criteria
* on `/spacewalk/bridge`
* The "To Pendulum" section design should be updated with new one.
* On the figma file all the screens under title "to Pendulum flow" should be implemented

## Brand assets
* Will share the icons for tokens

## Notes
* Disclaimer text, will be update on this ticket. 
* This ticket is just for the Pendulum version of spacewalk designs, will have a different one for Amplitude design update. 

## Wireframe
https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=419-616&mode=design

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/221?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by gonzamontiel** [comment]
hey hey, do you think we can get that disclaimer text @prayagd ? thank you :)

**Comment by prayagd** [comment]
@gonzamontiel Lets add loren ipsum now, i will create a new ticket for updating the disclaimer as there are couple of things and conditions ok?
