### ISSUE TITLE
 Update Pendulum Spacewalk "Transfers" page design

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#223]
As a portal user, i should see new "To Pendulum design" for the Spacewalk bridge

## Acceptance criteria
* on `/spacewalk/transfer`
* The table design should be updated.
* On the figma file all the screens under title "Transfer page" should be implemented

## Notes
* This ticket is just for the Pendulum version of spacewalk designs, will have a different one for Amplitude design update. 
* There will be a separate ticket to update the dailog boxes for the items from that table. 

## Wireframe
https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=419-616&mode=design

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/223?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by ebma** [comment]
Can you point to the specific screen in the design that should be used? There are just so many and they are not all the same but differ slightly. I wouldn't know which design to use.

**Comment by prayagd** [comment]
@ebma yes sure if you go to the above link, the designs are separeted with a heading. For this ticket i am referring to the screen with "Transfers page" heading.

**Comment by ebma** [comment]
Okay got it, so it's mostly about the row colors and having a proper heading at the top of the table.
The amplitude-themed design for the Transfers page was a little hard to find as it did not have the "Transfers page" heading in Figma. Can we maybe improve that structure a bit? I can see that the Figma indeed contains everything we need, it's just a little too hard to find.

**Comment by prayagd** [comment]
@ebma This is only for Pendulum, Following the rule of smaller tickets. We will have different tickets for Amplitude because the amplitude designs are also not ready. I mean a question here can we work only one version designs or both are connected with only color changes? cc @gonzamontiel 

Agree we are trying to structure it on figma, but you could not find Amplitude designs because they are not ready.

**Comment by prayagd** [comment]
@ebma ah, the earlier two tickets i created has pendulum missed in this ticket. Agree, Amplitude is priority i created this ticket so we can at-least get it estimated and started until the Amplitude design gets ready.

**Comment by ebma** [comment]
Sounds good. Can you please change the title and description to make it clear it's about Pendulum without having to read our comments then?

**Comment by prayagd** [comment]
I had already changed the description, but will update the title also now.

**Comment by prayagd** [comment]
@ebma Please estimate

**Comment by gonzamontiel** [comment]
Hey. What would the "To Amber" button mean? Is this something new or it's just a typo and it should be "To Amplitude" ?

**Comment by prayagd** [comment]
@gonzamontiel sorry not able to get you, can you please share a screenshot of what button you are talking about?
