### ISSUE TITLE
WalletConnect doesn't disconnect when wallet disconnects

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/portal#229]
### Describe the bug

When using WalletConnect with Nova Wallet (and every other wallet), the Disconnect button in the account dropdown from the Portal, does not trigger a disconnect session in wallet connect, producing that open sessions remain connected but are not 'in use'.

### Reproduction

1. Go to the Dashboard
2. Click on Connect to Wallet
3.  Chose Wallet Connect, a QR code appears
3. Open Nova Wallet in your phone (Settings -> WalletConnect), and scan the QR code 
4. Check that your session is active in Nova Wallet
5. On the portal, click on your account -> Disconnect
6. The session is still active and should be closed

### Expected behavior

We should manage the state of the session, or at least save a session identifier so we can then call disconnectSession function (as explained https://docs.walletconnect.com/2.0/web/web3wallet/wallet-usage#session-disconnect)

### Screenshots

![Screenshot_2023-08-09-10-11-39-94_e0c0d2a4a5b2406f6224f9f715ab5efa.jpg](https://images.zenhubusercontent.com/641c292481872ea4d8db8e72/423eb41e-0976-4596-8ab0-05985a59cca1)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/229?planning-poker) with Zenhub @ebma @gonzamontiel
