### ISSUE TITLE
Create dummy version of Spacewalk bridge UI

### ISSUE THREAD

**Issue by erasmus** [pendulum-chain/portal#23]
As a Spacewalk bridge tester, I want to test the complete flow of the bridge UI with dummy data. 

# Acceptance criteria 

This version will use dummy data, which is defined in this ticket. 

Add a notice: "This is a showcase prototype using dummy data. Spacewalk bridge is still in development." 

## Bridge input form (general UI)

* On `/bridge`, show bridge UI (see wireframes below)
    * Direction of bridge is by default _from_ Stellar _to_ Amplitude
* Bridge UI has 3 sections
    * On `bridge/issue`: the `Issue` (from Stellar to Amplitude)
    * On `bridge/redeem`: the `Redeem` (from Amplitude to Stellar)
    * On `bridge/transfers`: a list of pending/completed transfers

## Issue (Stellar to Amplitude UX)
* In `From` section:
    * show "From Stellar" as read only text
    * show `Input field` to enter token amount (allow same amount of decimals as all other number fields on app)
    * show `Dropdown` to select tokens (see hardcoded token list below)
* In `To` section: 
    * show "To Amplitude" as read only text
    * show _Received amount_
* Show button `Bridge` below the input form
     * Clicking on this opens a pop-up
* In pop-up, show:
    *  name of selected Stellar token 
    * Exact amount to send on Stellar network (e.g. `10 USDC`)
    * A timer (counting down from 24:00:00)
    * The `From` Stellar address  
    * The `To` Amplitude address
    * `I've made the transfer` button, which closes the pop-up
* On close, show the `Transfers` list with the state of the transfer as `Pending`

## Redeem (Amplitude to Stellar UX)
* In `From` section. 
    *  show "From Amplitude" as read only text
    * show `Input field` to enter token amount (allow same amount of decimals as all other number fields on app)
    * show `Dropdown` to select tokens. (see hardcoded token list below)
* In `To` section. 
    * show "To Stellar" as read only text
    * show _Received amount_ 
    * show `Input field` to enter Stellar address. 
* Show `Bridge` button. 
    * Clicking on it would execute the transfer.
* After execution, show the `Transfers` list with the state of the transfer as `Pending`

## Transfers
* Show the list of transfers with following parameters
    * _Time_
    *  _Amount_
    * _Transaction ID_
    * _Type_
    * _Status_

### Tokens to show in the issue dropdown
* `USDC`
* `TZS`
*  `BRL`

### Tokens to show in the redeem dropdown
* `sUSDC`
* `sTZS`
* `sBRL`

### Terms used in the wireframe
* From: `The network on which user has funds or wishes to bridge from`
* To: `The network on which user wants the funds or wishes to bridge to`
* Received amount: `The amount user would receive if the transaction is successful. For simplicity same as entered amount`
* Time: `Time when the transaction was executed.`
* Amount: `Amount of the transaction done`
* Transaction ID: `ID of the transaction. In issue Stellar ID, In redeem Amplitude ID.`
* Type: `Type of transfer. Issue or Redeem.`
* Status: `Pending, Completed and Failed.`

### Notes and assumptions
* All dynamic elements are highlighted in the wireframe. eg Input field, Dropdown and Buttons. 
* The timer countdown would start as soon as the bridge button is clicked. 

### Issue wireframe
![image](https://user-images.githubusercontent.com/52105313/197202747-f0441b53-ccd4-4a1c-ad71-2ae5369c8e1d.png)

### Pop-up wireframe
![image](https://user-images.githubusercontent.com/52105313/197202965-b8dfdd4c-2350-411c-9bc3-41bf0bfc7c6c.png)

### Redeem wireframe
![image](https://user-images.githubusercontent.com/52105313/197202999-e23d8f66-7a67-4964-a5ac-1353934a666c.png)

###  Transfer wireframe
![image](https://user-images.githubusercontent.com/52105313/197203022-fdcaec39-61b2-430f-8529-8aa181eb545b.png)

**Comment by nicolasdanelon** [comment]
@prayagd @erasmus guys you can check this here: https://pendulum-portal-alpha.netlify.app/amplitude/bridge

**Comment by prayagd** [comment]
@nicolasdanelon Just few changes we need to make here before closing
1. According to the wireframe in this ticket. It is called `Issue` and not `Swap`
2. In `Issue` wireframe the second part i.e the Amplitude part does not have a dropdown. Also does not have an input field. While the UI developed has it. The button on this screen is called `Bridge` not `Preview swap`
3. Same for the `Redeem` wireframe the second part i.e the Stellar one it has only one input field for the address no dropdown or any other input field.  The button on this screen is called `Bridge` not `Preview swap`
4. On `Redeem` after clicking `Preview swap` there should not be any pop-up.

**Comment by erasmus** [comment]
Closing as the this is the live version will replace this.
