### ISSUE TITLE
'Back to stellar' feature of the bridge not working

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#235]
### Describe the bug

Not able to execute the back to stellar request

### Reproduction

Steps to reproduce the behaviour:

1. Go to '/spacewalk/bridge' on the Amplitude network
2. Click on 'back to stellar'
3. Enter the amount, select the token to bridge and enter the stellar address 
4. Now click on the 'Bridge' button. The bridge button is unreponsive

### Expected behavior

User should be able to execute the back to stellar request. 

### Desktop (please complete the following information):

- OS:  iOS
- Browser: Brave

**Comment by prayagd** [comment]
cc @gonzamontiel

**Comment by gonzamontiel** [comment]
I observe these two errors, everything is back to normal on the Spacewalk side, right ?
![Uploading Screenshot from 2023-09-26 10.26.23.png…]()
![Screenshot from 2023-09-26 10 25 53](https://github.com/pendulum-chain/portal/assets/4713407/04fed9dd-5ffe-4b6a-8c7c-e0f0ff4dc28e)

**Comment by prayagd** [comment]
it should be @b-yap can you please confirm?

**Comment by ebma** [comment]
@gonzamontiel on which network and which screen do you see this error? I see those errors neither on Amplitude nor on Foucoco (Spacewalk pages) even when reloading the page many times to try all RPC nodes.

**Comment by gonzamontiel** [comment]
This is no longer happening on staging. You can check [here](https://staging--rococo-souffle-a625f5.netlify.app/amplitude/spacewalk/bridge).
