### ISSUE TITLE
Send to amplitude feature of the bridge does not work - transactions are cancelled

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#239]
### Describe the bug

The bridge of assets to amplitude is performed correctly, but after the transition to the pending state is not performed.

### Reproduction

1. Go to '/spacewalk/bridge' on the Amplitude network
2. Click on Bridge to Amplitude
3. Enter the amount, select the token to bridge, click on bridge
4. Perform the transaction on Solar wallet
5. Confirm - I have made the payment
6. Check the status of the payment in transfers 

### Expected behavior

After performed action the status of the transfer should change to pending and then to completed

### Browser
- Browser: Chrome

**Comment by annatekl** [comment]
cc @gonzamontiel

**Comment by gonzamontiel** [comment]
Currently, Spacewalk is not working due to an [issue with vaults](https://github.com/pendulum-chain/spacewalk/issues/394). I put this ticket on-hold till we fix the bridge itself and so we can test again in the Portal.

**Comment by gonzamontiel** [comment]
I haven't re checked yet, I will test it today and come back to you.

**Comment by ebma** [comment]
I can check the logs of the Amplitude vault clients tomorrow and see if I can find something related to that.

**Comment by ebma** [comment]
There are some issues that can only be resolved when we execute the next runtime upgrade unfortunately.

**Comment by gonzamontiel** [comment]
> There are some issues that can only be resolved when we execute the next runtime upgrade unfortunately.

Is the mentioned runtime upgrade already executed, is there anything we can do from the portal side ?

**Comment by ebma** [comment]
Runtime upgrade and root transaction are executed. There are a few bugs in the vault client that we are fixing now but it should be good next week.
