### ISSUE TITLE
Release Management

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#241]
### Context
We want to have portal releases. We learned that the currently the release management is already present in the flow but actually not configured. This ticket is to find out the way to setup the automatic flow that whenever new releases happen there should be release note should be published.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/241?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by gonzamontiel** [comment]
For semantic releases to work properly:
- Always name a PR using the semantic release keywords fix, feat, chore, etc (as explained [here](https://www.conventionalcommits.org/en/v1.0.0/#summary) , and defined by our semantic release config [here](https://github.com/pendulum-chain/portal/blob/staging/release.config.cjs)). In this case an example would be feat: my feature
- When squash & merging, the default commit message will be the PR title, which will automatically then trigger the semantic release action, change the version numbers and the changelog
