### ISSUE TITLE
Update Spacewalk "Back to stellar" design - Amplitude

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#246]
As a portal user, i should see new "Back to Stellar design" for the Spacewalk bridge

## Acceptance criteria
* on `/spacewalk/bridge`
* The "Back to stellar" section design should be updated with new one.
* On the figma file all the screens under title "Back to stellar" should be implemented

## Notes
* This ticket is just for the Amplitude version of spacewalk designs. 

## Wireframe
https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=2737-794&mode=design&t=0W3yUyip9JUKQSkE-4

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/246?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by ebma** [comment]
The 'back to stellar' design is missing a field to manually select the vault that is supposed to do the unbridging.

**Comment by prayagd** [comment]
@ebma 
1. TIL for me i used to thinking the vault that has issued the token would be the one issuing it back hence no selection. Based on your comment i learn that is not the case right? So will here is new [ticket](https://github.com/pendulum-chain/portal/issues/249) just to replicate the vault designs in the redeem side too. @gonzamontiel Let me know if the new ticket is clear enough?
2. You are right, the redeem might be oversight from our end. Will get it fixed.

**Comment by ebma** [comment]
> TIL for me i used to thinking the vault that has issued the token would be the one issuing it back hence no selection. Based on your comment i learn that is not the case right?

Yes, you can redeem your wrapped asset with any vault that supports this asset (and holds enough bridgable tokens on Stellar, ie. bridged enough assets for other users previously).

> So here is new https://github.com/pendulum-chain/portal/issues/249 just to replicate the vault designs in the redeem side too. @gonzamontiel Let me know if the new ticket is clear enough?

Looks good.

**Comment by prayagd** [comment]
The designs are fixed now. @gonzamontiel can you please add estimates?
