### ISSUE TITLE
Update Spacewalk "To Amplitude" Design

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#247]
As a portal user, i should see new "To Amplitude design" for the Spacewalk bridge

## Acceptance criteria
* on `/spacewalk/bridge`
* The "To Amplitude" section design should be updated with new one.
* On the figma file all the screens under title "to Amplitude flow" should be implemented

## Notes
* This ticket is just for the Amplitude version of spacewalk designs.

## Wireframe
https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=2737-3232&mode=design&t=0W3yUyip9JUKQSkE-4

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/247?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by ebma** [comment]
I find the design for selecting a vault confusing, I suppose the dialog is supposed to open when you click on the cog wheel?

**Comment by prayagd** [comment]
@ebma Yes the dailog opens, only when you click on the cog wheel. Can you please elaborate what is confusing?

**Comment by ebma** [comment]
All good, I just was not sure how the 'Select Vault' dialog suddenly appeared but that's more an issue with the Figma and not the designs itself. Didn't we also have 'flow' design board that showed transitions between screens? @prayagd can you send me the link to this again, I can't find it anymore 👀

**Comment by gonzamontiel** [comment]
Good point @ebma , I have the flows but with the old designs [here](https://www.figma.com/file/XLIKffEYnK9autHMM1YgA3/Flows?type=whiteboard&node-id=0-1&t=2G02qLey91iAgORk-0), I guess both files are unrelated.
Also, I updated the ticket's title to reflect Amplitude's design.

**Comment by ebma** [comment]
Okay, thanks for clarifying @prayagd

**Comment by prayagd** [comment]
@gonzamontiel can you please add your estimates?
