### ISSUE TITLE
Allow users to redeem their swap pool deposit from the backstop pool

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#250]
Example of the UI on the swap pool withdrawal screen:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2lEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c6d1f5803e645f5c7772828e45ba72c2de9efb81/image.png)

**Comment by prayagd** [comment]
closing this older ticket
