### ISSUE TITLE
Adding the link to the EURC issuer's web page for on and off ramp - Portal

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#254]
Redirect link to a hosted webpage by Mykobo for the EURC on-ramp and off-ramp
Addition of a new row on Pendulum portal will enable the minting of EURC tokens through the Mykobo webpage

Requirements:
- new row in the "Mint EURC" section of the portal, accessible to Pendulum portal users.
- users are redirected to hosted by Mykobo webpage

**Comment by vadaynujra** [comment]
@prayagd designs to be kicked-off.

**Comment by prayagd** [comment]
Closing this as not relevant anymore
