### ISSUE TITLE
Metamask snap Integration

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#257]
### Context
So Metamask has built snaps that allows metamask to interact with dApps apart from the ethereum ecosystem. We would like to integrate this into our Portal. So metamask users can interact with our Portal. 

## Requirements

- [ ] Here is the detail description of the integration [process](https://github.com/chainsafe/metamask-snap-polkadot/wiki#integration)
- [ ] Show Metamask as option in the wallet connect dialog box
- [ ] Icon - 
![image](https://github.com/pendulum-chain/portal/assets/52105313/153699e9-26ec-4fed-baa4-9e9cbb7a507f)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/257?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by prayagd** [comment]
also @gonzamontiel let me know if this is helpful to proceed on this ticket?

**Comment by gonzamontiel** [comment]
Hey it looks good, I will fetch the metamask icon from somewhere.

**Comment by prayagd** [comment]
Why somewhere i can get it for you 😅
