### ISSUE TITLE
Add AMPE price to the dashboard

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#258]
### Context
AMPE is now live on Zenlink and has price, It would be good if we start showing the AMPE price on the Portal dashboard. 

## Requirement
* Show AMPE price on Portal dashboard
* How to get AMPE price?
    * Query the [squid](https://squid.subsquid.io/amplitude-squid/graphql) 
    * Here is the sample query

```
query MyQuery {
  bundleById(id: "1") {
    ethPrice
  }
}
```

Also mentioned my @ebma in the below [comment](https://github.com/pendulum-chain/portal/issues/258#issuecomment-1739696968)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/258?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by ebma** [comment]
Maybe it's better to query that data directly from our squid. 
You can get the price from https://squid.subsquid.io/amplitude-squid/graphql with the following query
```
query MyQuery {
  bundleById(id: "1") {
    ethPrice
  }
}
```
`ethPrice` represents the price of AMPE in USD. I know the naming is confusing but we adopted it from the Zenlink squid.

**Comment by prayagd** [comment]
@ebma updated in the original message
