### ISSUE TITLE
Update design for staking to a collator

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#263]
As a portal user, i should see new design for staking flow

## Acceptance criteria
* on `/staking`
* On the figma file all the screens under title "Stake flow" should be implemented

## Notes
* This ticket if for both versions
* This is only for desktop

## Wireframe
https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=2849-5156&mode=design&t=75cQjduNPnz4bezE-4

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/263?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by ebma** [comment]
Is the responsive/mobile-friendly design also part of this ticket?

**Comment by prayagd** [comment]
No, will create a separate ticket for that. Also will update in the ticket
