### ISSUE TITLE
Update design to update and claim staking rewards

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#265]
As a portal user, i should see new design for update and claim staking rewards

## Acceptance criteria
* on `/staking`
* On the figma file all the screens under title "update reward flow" and "claim flow" should be implemented
* Once the user updates the reward, disable the update button for 15 minutes

## Notes
* This ticket is for both versions

## Wireframe
Update flow - https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=3235-1093&mode=design&t=t1rNti6sG2YwCnwQ-4

Claim flow - https://www.figma.com/file/5up5sghcttBogehUq4255i/App?type=design&node-id=2849-4822&mode=design&t=t1rNti6sG2YwCnwQ-4

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/265?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by ebma** [comment]
Can we get rid of the Lorem ipsum texts?

**Comment by prayagd** [comment]
Sure, will add specific texts there

**Comment by gonzamontiel** [comment]
Hey @prayagd, can you please confirm that the mobile designs doesn't apply to this version yet? I just want to make sure. 
Like our responsiveness would look as follows in tinier mobile screens (which is not exactly the mobile designs, but it is usable):
<img width="470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGxWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--061a2149808ce04ee2d279adc60741f2b0ac6bbe/Screenshot%20from%202024-02-13%2015.05.18.png" alt="Screenshot from 2024-02-13 15.05.18.png" />
