### ISSUE TITLE
Fix contract transaction execution

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#269]
There is an issue with depositing and withdrawing funds from pools by using the useContractWrite hook. The transactions seemingly complete successfully but the queried balance does not reflect any changes.

Based on discussions with Tosten it is better to use the `@pendulum-chain/api-solang` to execute contract call as it gives more information about the errors and failures.

Goals:
1. Refactor contracts calls to use `@pendulum-chain/api-solang` library
2. Debug and fix contract method calls (deposit, withdraw, ...) when using useContractWrite hook

**Comment by nejcm** [comment]
Tagging for visibility and support. @ebma

**Comment by ebma** [comment]
@prayagd you probably meant to ping @TorstenStueber.

**Comment by prayagd** [comment]
oh yes

**Comment by TorstenStueber** [comment]
Yes, we can close, all of this has been done on the Nabla branch.
