### ISSUE TITLE
Get PEN for gas using any token from the Pendulum network

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#277]
As a portal user, i should be able to get PEN using DOT/USDT/GLMR/USDC for gas fees

## Acceptance criteria
* on `portal.pendulumchain.org`
* Next to network selection dropdown show "GET PEN" button, on clicking this button
* on `/gas` show 
    * Input field "Swap from" with min and max, user should be able to enter only the values between min and max or just select min or max
    * Dropdown for tokens, user should be able to select one
    * Text field "Swap to" with PEN, user should be able to see the amount of PEN token they recieve
    * Below the text field one more text field showing the amount of transactions that user can be do with the amount of PEN the user is getting (How to calculate this? Added in Notes)
    * Button "GET PEN", on-clicking execute the on-chain transaction
* on successful onchain transaction show a pop-up saying "You have successfully purchased PEN"
* in the lorem ipsum text of the pop-up "X transactions can be executed using X PEN"

### Notes
* Min and Max can be fetched from the runtime
* Tokens to show in dropdown for Pendulum network - DOT, USDT, GLMR, USDC
* To calculate amount of transactions = gas cost for single transaction * PEN tokens
* Tech provides the gas cost of single transaction
* Insufficient funds tool tip to only be show when PEN balance is zero

### Technical considerations
- Fetch min amount with `api.consts.treasuryBuyoutExtension.minAmountToBuyout`
- Fetch sell fee with `api.consts.treasuryBuyoutExtension.sellFee`. The sell fee is given as a fixed point number so if you want to use it for calculations you'd first need to transform it to a decimal number with [this](https://github.com/pendulum-chain/portal/blob/b5bccf73f57a7705b5feefa030dd218f0262d851/src/shared/parseNumbers.ts#L42) helper function
- Fetch max amount with `api.storage.treasuryBuyoutExtension.buyoutLimit()`
- To calculate the gas cost for a simple transfer extrinsic you can follow [these](https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-estimate-the-transaction-fees) steps. The `partialFee` parameter is the one you are interested in. You can then compare the `partialFee` to the amount of PEN that the user wants to receive to derive the number for the 'X transactions can be executed using X PEN' text. 

To calculate the amount the user will receive you need to follow [this](https://github.com/pendulum-chain/pendulum/blob/e85eb59ed30188162d7a0172e170c5872a111172/pallets/treasury-buyout-extension/src/lib.rs#L370-L378) calculation. The `basic_asset_price` is the price of the native token, ie. PEN in this case. The `exchange_asset_price` is the price of the token that you are trying to use for the buyout ie. DOT/USDT/GLMR/USDC. Token prices can be retrieved with [this](https://github.com/pendulum-chain/portal/blob/b5bccf73f57a7705b5feefa030dd218f0262d851/src/hooks/usePriceFetcher.ts) hook. The `multiply_by_rational(a,b,c)` function performs `a * b / c` so you can replace it with those simple operations.

### Wireframe
https://www.figma.com/proto/5up5sghcttBogehUq4255i/App?type=design&node-id=3990-6171&t=OlE9kHP0w5nXV9Ck-1&scaling=min-zoom&page-id=3979%3A1234&starting-point-node-id=3990%3A6171&show-proto-sidebar=1&mode=design

**Comment by prayagd** [comment]
@ebma can you please provide the technical details or how to fetch them for @Sharqiewicz

FYI, the designs are ready but not titled and separated on the figma page. Would be done by EOD

**Comment by ebma** [comment]
Done

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/277?planning-poker) with Zenhub @ebma @gonzamontiel @Sharqiewicz

**Comment by prayagd** [comment]
Updated the figma file, now its a prototype(clickable) file for better understanding the flow

**Comment by prayagd** [comment]
@Sharqiewicz is this blocked due to some reason?

**Comment by Sharqiewicz** [comment]
Blocked until [https://github.com/pendulum-chain/pendulum/issues/460](url) is finished.
