### ISSUE TITLE
Add info to the swap pool withdraw and deposit UI

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#285]
**Deposit UI**

- [ ] Calculate deposit amount to swap pool LP token (show how much LP you will get)
- [ ] Show slippage and fee info

**Withdraw UI**

- [x] Calculate withdraw amount from swap pool LP token (show how much of the asset you will receive from LP)
- [ ] Show slippage/fee info

**Comment by prayagd** [comment]
Closing older ticket
