### ISSUE TITLE
UI - add new assets (NGN, EUR and AUD) for the Spacewalk bridge

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#290]
### Context
As there is a spacewalk public launch coming on Amplitude, the new assets should we shown on the portal UI. 
This ticket requests the integration of new assets (NGN, EUR and AUD) into the Spacewalk portal's user interface.

### Describe the feature you'd like:
* Integrate Assets into Spacewalk Portal UI
* Design and implement the user interface (UI) for Spacewalk portal to include NGNC, EURC, and AUDD assets.
* Ensure that users can easily access, view, and interact with these newly added assets.
* This is to be done only on the Amplitude version of spacewalk

### Icons
https://drive.google.com/drive/folders/15g9YrUqFs8PmWyMV65PRFGj4Z97F2N6t?usp=drive_link

**Comment by prayagd** [comment]
@ebma would these new assets automatically show up on the portal?

**Comment by ebma** [comment]
No, additional work is required. Can you please try to provide the icons that are supposed to be used for NGNC, EURC and AUDD?

**Comment by prayagd** [comment]
Icons updated to the main description please let if know if its not accessible

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/290?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by prayagd** [comment]
Yes

**Comment by gonzamontiel** [comment]
A PR is ready to handle these assets, but keep in mind that I cannot possibly test the full workflow since the available assets are provided by the bridge (more specifically, by the available vaults that provide those assets). So far, I didn't see the new tokens available on Spacewalk, correct me if I'm wrong.

**Comment by ebma** [comment]
> So far, I didn't see the new tokens available on Spacewalk, correct me if I'm wrong.

That's correct, we haven't registered vaults for the new assets yet. We'll do that soon as part of [this](https://github.com/pendulum-chain/tasks/issues/166) ticket.

**Comment by gonzamontiel** [comment]
Okay, do you want to pause [this PR](https://github.com/pendulum-chain/portal/pull/302) until that happens? otherwise it can be approved I guess.

**Comment by ebma** [comment]
No need to pause, I approved it and it can be merged 👍
