### ISSUE TITLE
Show Nabla preview on staging

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#299]
On staging add a new env variable:

`VITE_ENVIRONMENT=staging`

**Comment by prayagd** [comment]
@nejcm Please add the steps for this

**Comment by nejcm** [comment]
@gonzamontiel You can take over.

**Comment by gonzamontiel** [comment]
I added the variable on Netlify deployments. This takes effect in https://portal.pendulumchain.org/, can you check @nejcm that what you were expecting happened ? The ticket is not clear of what is expected to happen.

**Comment by nejcm** [comment]
So essentially the nabla endpoint should become available and the menu item should be visible. Will confirm

**Comment by nejcm** [comment]
Ok confirming that it works. I see only a small issue. It's still grayed out on pendulum side but ok on foucoco

**Comment by prayagd** [comment]
@nejcm this also started showing Nabla menu item on Amplitude, which was not present there earlier

**Comment by nejcm** [comment]
So the current logic works in a way where the menu is always there but clicking on it shows you either the ui or a message that you have to switch to the correct network to use nabla (foucoco). We can change this logic.

**Comment by prayagd** [comment]
@nejcm it would be better we remove this as menu item from Amplitude version completely just to avoid any confusion.

**Comment by nejcm** [comment]
Ok. Will make a fix for it

**Comment by prayagd** [comment]
Thank you
