### ISSUE TITLE
Update the disclaimer text for bridge UI

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#300]
## Context

We want to update the disclaimer text for Amplitude version of spacewalk bridge

### Text to be updated

- Issue Fee: 0.10% of the transaction amount.
- Redeem Fee: 0.10% of the transaction amount.
- Security deposit: 0.50% of the transaction amount.
- Max issuable amount: 20,000 USD
- Estimated time for issuing: 2mins - 3hrs (only applicable after the user makes the stellar txn to the vault)

**Comment by prayagd** [comment]
@ebma would you be able to provide a approximate range of time that it takes to issue? for ex. 30min - 7hrs something like this?

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/300?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by ebma** [comment]
@prayagd uhm well if all goes well it would take just about 1 minute for bridging (after the user submitted the respective payment transaction on Stellar). If it doesn't then it might be resolved with the vault's next periodic restart, which happens every 3 hours.

**Comment by prayagd** [comment]
@ebma so how about 2mins - 3hrs?

**Comment by ebma** [comment]
Yeah, why not. But it's important that this is the time **after the user submitted the respective payment transaction on Stellar**. We need to include this info in the info text. It's not the time after creating the issue request. If the user never submits the payment on Stellar, the vault will not execute the issue.

**Comment by annatekl** [comment]
@gonzamontiel can you update me on the progress of adding the disclaimer?
