### ISSUE TITLE
Make line item from the spacewalk transaction history clickable

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#311]
As a user, i should be able to click on the spacewalk transaction to see the details

## Acceptance criteria
* On /transfers
* On clicking the line item from the transfer table, this should open up the pop-up
* The entire line item should be clickable.

## Note
* Currently the `Request ID` is clickable and copyable, this should not be possible anymore
* Line item
<img width="1123" alt="Screenshot 2023-12-12 at 6 27 33 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/37de734a-0a92-47c0-bce4-09a49005c12f">

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/311?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by gonzamontiel** [comment]
The only thing to decide here is what to do when you click on the copyable address. It could be that you accidentally click there to open the dialog, and then: the dialog opens, the address gets copied, and a toast opens at the same time, resulting in a confusing UX.
