### ISSUE TITLE
Vertical scroll missing on account selection in the connect wallet flow

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#328]
### Describe the bug

User is not able to select the account of choice from the options as some options arent accecsible due to vertical scroll is missing

### Reproduction

1. Go to portal.pendulumchain.org
2. Click on Connect wallet
3. Choose a suitable option
4. Now see a list of accounts to choose from, Limited options visible. No vertical scrolling to choose from more options

### Expected behavior

Vertical scroll should be present to selection other options from the available one's

### Screenshots

![image](https://github.com/pendulum-chain/portal/assets/52105313/9fc709b4-e8ad-4395-a530-67336a0f4eda)

### Desktop (please complete the following information):

- OS: iOS
- Browser: Brave

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/328?planning-poker) with Zenhub @ebma

**Comment by ebma** [comment]
I'm estimating this as a 5 because I think this is an issue in a third-party package we are using so we can only fix it by creating our own dialog. Didn't we talk about creating a custom wallet selection dialog some time ago @prayagd? Do we already have a ticket for this?

**Comment by prayagd** [comment]
@ebma the placeholder ticket was there, the designs are also now ready. Will update that ticket, So what is your suggested approach here? should we directly jump on that ticket and skip this one?

**Comment by ebma** [comment]
Can you share a link to the other ticket (if there is any)? I'd like to look at it before taking a decision

**Comment by ebma** [comment]
I'm hesitating to start working on this ticket. As I said, I think it would be best to completely replace the existing account selection dialog as we are using the component from Talisman and it's not perfectly customizable. I don't know what to base the design on though. Would this be defined in ticket #28 @prayagd? Do you want it to look very similar to how it looks right now or should it be different?  Please share your thoughts so that this ticket can be worked on.

**Comment by prayagd** [comment]
@ebma it would be completely different, i have shared the new design with you on slack. Will also close this ticket as prepare that one, so we dont end up doing double work.
