### ISSUE TITLE
Nabla contract method issues

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#330]
## Issues
These are some issues that are faced when interacting with the Nabla smart contract

* Backstop pool deposit fails with description: reverted: Call to chain_extension failed.
* Router contract getAmountOut fails with: Error: createType(u256):: u256:: Decoded input doesn't match input, received `0x08c379a07c43616c6c20746f20636861696e5f657874656e73696f6e206661696c65642e` (36 bytes), created `0x08c379a07c43616c6c20746f20636861696e5f657874656e73696f6e20666169` (32 bytes)

**Comment by prayagd** [comment]
cc @nejcm @ebma

**Comment by prayagd** [comment]
@ebma Please add your estimates and move it appropriately if already started working

**Comment by ebma** [comment]
@TorstenStueber can I hand this to you as you already identified the problem of the second issue?

**Comment by TorstenStueber** [comment]
@ebma Sure. But I think we will not create a new branch to fix it, but incorporate changes directly in https://github.com/pendulum-chain/portal/pull/326 (as these errors have been indentified as part of the review).

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/330?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by prayagd** [comment]
@TorstenStueber is this ticket done? should we close?

**Comment by TorstenStueber** [comment]
I close when everything is done and merged.

**Comment by ebma** [comment]
@TorstenStueber should we close it now?

**Comment by TorstenStueber** [comment]
Sure, this is long outdated.
