### ISSUE TITLE
Enable the Spacewalk option from menu on Pendulum network

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#333]
## Context
For users to access Spacewalk on Pendulum, it should be enabled on the menu

## Requirements
* Enable the Spacewalk menu item and the sub menu items
* Port over the token icons from Amplitude to the Pendulum version in the spacewalk token dropdown
* Add these icons to the Pendulum dashboard

**Comment by vadaynujra** [comment]
Thanks @prayagd, good to know that this is the only ticket required for enabling Spacewalk on Portal for Pendulum.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/333?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by prayagd** [comment]
@gonzamontiel Let me know if anything missing with respect to the tokens i.e icons or prices
