### ISSUE TITLE
General Nabla TODOs

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/portal#348]
- [x] The deposit popup for Swap Pools and Backstop Pools intends to show a fee, but it only shows TODO
- **Question**: What is "My Pool Amount" on the Swap Pool overview? I now write the number of LP tokens the user has, is that right?
* **Question**: The "Pool liabilities" shows the "total liabilties" of the Swap Pool page – instead we should show the total number of LP tokens (which is not the same)
- [ ] Many buttons to perform actions in Nabla require two steps: first press is a token approval, the second press is the actual action. Instead we can wrap both steps into one batch transaction so that the user only has to sign one transaction
  - to be done later, we first need to update to Polkadot version 1.6.0 or later
- [x] I added better error messages when the user wants to execute a swap but the token amount is too high to be successful. This is an error message in red in the "
- [x] It is not reasonable that we format numbers by the locale of the user when everything else is in English
   - [x] I already changed this now and always use the en-US locale for formatting numbers. The reason was that some Nabla code wanted to reparse these numbers and assumed that they use the English format.
* **Question**: We sometimes use token names and sometimes just token symbols (which is an abbreviation of the token name), confusing? E.g., on the swap pool overview we write token names in the table but in the modal for executing deposits we write the token symbol.
- [ ] Sometimes the contract calls fail for good reasons, but we cannot display a proper error message, we just show a general error. For example if the user wants to deposit an amount into the swap pool but does not have enough tokens. I created [a ticket in the Nabla contracts repository](https://github.com/0xamberhq/contracts/issues/94) that allows to display better error message.
- [x] There are information icons on some screen (an "i" in a circle), e.g., on the Swap form. These icons have a tool tip that just shows "TODO"
- [x] Remove all debug output on the console

## Urgent
- [x] The `getTotalPoolWorth` method of the deployed backstop pool returns in an unspecified error. For that reason some of the backstop pool functions don't work.
- [x] Swaps sometimes don't work and the contract execution just generates an error (e.g., swapping 100 NAT for X0 for the user `6jErEgivAvJmfN2kUNsECqRBk1xkp8XBYAfxntvReSoxxRjy`)

**Comment by prayagd** [comment]
@TorstenStueber should we close this ticket, assuming all of this is done?

**Comment by TorstenStueber** [comment]
I went through the list and marked what is done, what is still open and marked what items are actually questions to @pendulum-chain/product. Can you give some comments to these questions and decide whether we should act on them?

**Comment by prayagd** [comment]
> What is "My Pool Amount" on the Swap Pool overview? I now write the number of LP tokens the user has, is that right?

Exactly what it is

> The "Pool liabilities" shows the "total liabilties" of the Swap Pool page – instead we should show the total number of LP tokens (which is not the same)

This should be addressed in the #474 

> Question: We sometimes use token names and sometimes just token symbols (which is an abbreviation of the token name), confusing? E.g., on the swap pool overview we write token names in the table but in the modal for executing deposits we write the token symbol.

We agreed on using the token symbols

**Comment by TorstenStueber** [comment]
@prayagd I would favor if we can close this ticket and open new focused tickets instead. Most points are already defined in new tickets anyway (is the token name -> token symbol issue addresses already?)
