### ISSUE TITLE
Remove the staging branch

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#368]
## Context
Following the suggestion from the tech team, this ticket is to remove the staging branch and from here on merge the ticket directly to the main branch for continous releases. 

## Requirements
* Remove staging branch
* Merge reviewed tickets directly to the main branch i.e Production
* Merge tickets should show up in the Changelog

**Comment by ebma** [comment]
@Sharqiewicz I guess we can close this now that we have https://github.com/pendulum-chain/portal/pull/370?

**Comment by prayagd** [comment]
Closed
