### ISSUE TITLE
Update the note text on the spacewalk "to Pendulum" flow

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#380]
## Context
Currently the note text on the attached pop-ups is not very clear as it mentions the minimum amount to time required by the vault to execute the request. Expected to all also mention the maximum time i.e 3 hours

## Requirement
* On creating a "to Pendulum" request on spacewalk, in pop-up displayed to make the transfer to the vault the note text to be updated
* Updated note text is "Note: Estimated time for issuing is in a minute after submitting the Stellar payment to the vault, contact [support](https://t.me/pendulum_chain) if your transaction is still pending after 10 minutes."
* Another pop-up to update the note text is the "Pending" status pop-up in the "to Pendulum". Reference attached

## Note
* To be updated on both networks Pendulum and Amplitude

## Reference 
![image](https://github.com/pendulum-chain/portal/assets/52105313/ab021764-8b4c-43c9-b836-65b398e79f48)
![image](https://github.com/pendulum-chain/portal/assets/52105313/9507e09b-b676-4859-b1ab-abe0f370360e)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/380?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by ebma** [comment]
> "Estimated time for issuing is minimum 2 mins or maximum up to 3 hrs (after submitting the Stellar payment to the vault)."

Can we rephrase the part about the minimum? The minimum time is not 2 minutes. After submitting the payment to the vault, the vault could complete the bridging within just 1 minute though we can't guarantee that and it depends on the network latency of the Stellar network and Pendulum etc. But 2 minutes is an arbitrary value whereas the phrasing indicates that this is some hard limitation that we are facing here. 

How about we rephrase to 

> "Estimated time for issuing ranges from a minute to a maximum of up to 3 hrs (after submitting the Stellar payment to the vault)."

**Comment by prayagd** [comment]
@ebma make sense, updated the main description with your suggestion
