### ISSUE TITLE
Update the disclaimer text

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#382]
## Context
The disclaimer text on the spacewalk feature has typos and need to be fixed

## Requirement
* Go to /spacewalk/bridge
* Update the disclaimer section with following text

• Bridge Fee: Currently zero fee, transitioning to 0.1% per transaction soon.
• Security deposit: 0.5% of the transaction amount locked, returned after successful issue/redeem
• Total issuable amount (in USD): 20000 USD. Join our vault operator program, more [here](https://pendulum.gitbook.io/pendulum-docs/build/spacewalk-stellar-bridge/operating-a-vault).
• Estimated time for issuing: In a minute after submitting the Stellar payment to the vault, contact support[https://t.me/pendulum_chain] if your transaction is still pending after 10 minutes.

## Notes
* Please make longer texts are indented and dont come under the bullet point. See screenshot
<img width="369" alt="Screenshot 2024-03-22 at 6 12 23 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/61119fc6-21bb-4306-bfba-41519e58b740">

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/382?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by ebma** [comment]
Can we change the phrasing of the estimated time for issuing here as well?
