### ISSUE TITLE
Fix the DOT price on the portal dashboard

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#383]
### User Story
As a user with DOT on Pendulum, I want to see in the Balances view, the correct amount of DOT I own, so that I am aware of my accurate holdings.

### Requirement
- [ ] Update the UI such that it considers DOT to have 10 decimals, instead of 12

Current view

<img width="1254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2d2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2db374fdace1fbdb87aa4ac3ca82435a6a7a75aa/image.png" alt="image.png" />

Actual amount in account - 0.5 DOT

**Comment by vadaynujra** [comment]
@prayagd I marked this as a bug, added some details.
