### ISSUE TITLE
Add QR code for issue requests on Spacewalk

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/portal#395]
### User Story
As a mobile wallet user, using the portal on the desktop, I want to be able to scan a QR code encoded with the amount of issue request, vault address to the receiver and the memo, so that I can easily make the transfer without missing details.

### Requirement

- [ ] Show QR code encoded with amount of issue request, vault address and the unique memo of the transaction on the issue request pop-up
- [ ] Show this QR code below the vault address with text "OR" followed below by QR code
- [ ] User should be able to scan the QR code with stellar mobile wallet, which should prompt a send request in the wallet with all the encoded details
- [ ] Add a button "Sign txn" in the issue pop below the QR code for browser wallet users, clicking on this should prompt the users browser wallet with all details regarding the issue txn

### Notes

The content of the QR code will be a URI adhering to the schema described in [this](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0007.md#operation-pay) protocol. We can only focus on the `pay` operation as it is fulfills the need we have here. To create the QR code we can use any QR code library that we will then use to generate a QR code for URIs similar to `web+stellar:pay?destination=<vault_stellar_account>&amount=<issue_amount>&memo=<issue_request_memo>&memo_type=MEMO_TEXT&msg=<my_custom_message>`
**Note**: the button should act in the same way as clicking on a link with the `href` being the same URI as for the QR code.

**Comment by vadaynujra** [comment]
@prayagd are the details in [this](https://medium.com/lumenauts/stellar-payments-thoughts-on-federation-qr-codes-uris-and-point-of-sale-systems-within-the-2c6fcdc3fa4d) article enough to detail this ticket?

**Comment by prayagd** [comment]
@ebma i have linked the repo to create a stellar txn QR, please check and let me know if that is sufficient for this ticket? Let me know if any feedback or comments cc @Sharqiewicz

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/395?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by ebma** [comment]
I updated the notes section and I think it's okay now.

**Comment by prayagd** [comment]
added the button for the browser wallet users
