### ISSUE TITLE
Adjust the text for Spacewalk issue request - deposit screen

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#399]
### User story
As a user, I want view the complete address of the issuer in the popup window when creating an issue request, so that I can easily identify who issued the asset. 
At the moment, the issuer's address is not fully visible, or copyable.

### Requirement
- [ ] Make the issuer's address copyable similar to vault address and memo
- [ ] Applicable to both networks Pendulum and Amplitude

### Reference

<img width="493" alt="Screenshot 2024-04-09 at 13 08 16" src="https://github.com/pendulum-chain/portal/assets/138758794/66c88df1-4aa3-452f-ae4d-595adf9dcef8">

**Comment by vadaynujra** [comment]
@annatekl we should also specify what 'information' needs to be displayed and how. So, if you want to be able to copy it, or just be able to read it in full, but not copy it, or click a link that opens the Stellar.expert page of that issuer. There are many solutions for how this could be implemented. Maybe do some user interviews to define fully?

**Comment by annatekl** [comment]
to be consistent with other data that we present we can go with fully copy as we do for memo and in single transaction too. But i think direct opening in the Stellar wallet is ideal. WDYT?

**Comment by vadaynujra** [comment]
In the current UX, the memo and the account address need to be copied by the user, as they need to add that on the Stellar transaction. 
The issuer's address needs to be confirmed. What is the journey we want the user to do, to confirm this @annatekl

**Comment by annatekl** [comment]
just checked the stellar wallet and it looks like the user can search for the asset issued by a certain issuer only when the full sequence is provided. So we need to make sure the below criteria are met: 
Full Sequence Requirement: The user needs to be provided the full sequence to perform this search.
Presentation of Issuer Data: presenting issuer data similarly to memos and account addresses, with a copy icon. @vadaynujra

**Comment by prayagd** [comment]
@annatekl Based on your last comment, i have updated the ticket. Will get it estimated and ready to develop

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/399?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by annatekl** [comment]
@Sharqiewicz where is the PR to this ticket?
