### ISSUE TITLE
Redeem tokens on Stellar network - Spacewalk

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#40]
As a wrapped stable coin holder on Amplitude network, I want to bridge my tokens back to Stellar.

# Acceptance criteria
* On `\bridge`
* At top of the page show warning
   * Currently in beta mode. Transactions are capped to $9999. 
* Show `Issue` and `Redeem` tab. 
* In `Redeem`. Show Input field and a dropdown next to it
   * Input field to enter the amount of tokens to be bridged.
   * Dropdown to select the token tickers.
* Below this show one more input field. To enter Stellar address. 
* Next show the amount of tokens and the token ticker to be received on Stellar
* At the bottom show `Confirm` button. On click opens-up a pop-up.
* In pop-up
   * Show tokens redeemed and their value in dollars.
   * Show the stellar address the tokens are sent to.
   * At the bottom of pop-up show button `View Progress`
* On clicking `View Progress` pop-up closes and directs you the particular transfer on `\transfer`

### Notes
* Following ticket is written based on assumptions that vaults and fee structure are not defined. 
* Input field - Inputs only until two decimals allowed. 

### Wireframe
Will update once ready

# Technical consideration
To be filled in by the tech-team.

**Comment by prayagd** [comment]
@ebma Can you please help with these questions? Please add the response under technical consideration in the above message
* How to fetch the tokens tickers for the dropdown. 
* How to initiate transaction once the user clicks confirm?

**Comment by prayagd** [comment]
@ebma Should i move this to backlog as this currently paused?

**Comment by ebma** [comment]
@prayagd no need as I will continue with that today
