### ISSUE TITLE
Show list of spacewalk transfers

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#41]
As a Stellar and Amplitude user, I should be able to track the status of my transfers on spacewalk. 

# Acceptance criteria
* On `\transfers`
* Show two categories `Issue Requests` and `Redeem Requests`.
* Show list of previous transfers under `Issue` and `Redeem` respectively.
* Show following information in the list. 
   * Date and time
   * Amount
   * Stellar transaction
   * Status (Completed, Pending and Failed)
* On clicking any of the list item. 
   * Show a new page with additional details of the transaction.
      * Parachain block
      * Destination address
      * Vault account
      * Stellar transaction ID (Only for issue requests)
      * Received amount of tokens (only if status completed)

### Wireframe
Will update once ready

# Technical consideration

* Use Spacewalk pallets storage to access the requests 
* Precisely, we need to call `api.query.issue.issueRequests.entries()` and `api.query.redeem.issueRequests.entries()` to retrieve such information
* Parse the information to extract the required data

**Comment by prayagd** [comment]
@ebma Can you please with the following questions? Please add the responses under technical consideration in the above message. 
* How to fetch the above listed details?

**Comment by gonzamontiel** [comment]
> Show a new page with additional details of the transaction.
> - Parachain block
What do you expect to see here @prayagd ? If it was the block in which the transaction was finally included (i.e. the Pendulum chain block where the mint/burn happened), then we don't have a direct link between the transfer object in spacewalk and that information.
This is something that we could extract having an indexer. Then, we could ask the index, for example, for all the transactions (extrinsics) of type `issue.executeIssue` and then filter the one that we care about, and then, get the block number of that transaction. 
I cannot think of another easy way, @ebma anything to add?

**Comment by ebma** [comment]
I also can't think of an easy way to show the block number for an extrinsic. And I think it's not that important to have that information as a user. 

As @gonzamontiel, we would probably only be able to show that once we have an indexer, so I'd suggest we drop that number as a whole from the dialog. While we could show the `openTime`, ie the number of the active block when the request was opened, the user can't do anything with that information and it might confuse more than it helps.

**Comment by prayagd** [comment]
@gonzamontiel Ok for this iteration we can drop the Parachain block number from this release as i understand it is high effort to get it now. @ebma Dont agree that this is not useful information. I mean yes instead of showing the block number we can show the txn id as it is good UX to see that the transaction has actually happened on the blockchain.
