### ISSUE TITLE
Fetch allowed currencies and native currency from blockchain

### ISSUE THREAD

**Issue by Sharqiewicz** [pendulum-chain/portal#410]
Now Portal is using hardcoded data to show the GET AMPE swap form. ( useBuyout/utils.ts )
We want to use the metadata from the blockchain instead of the hardcoded one.

1. Fetch allowed currencies from the blockchain.
2. Fetch native currency from the blockchain.
3. Handle errors related with undefined data fetched from the blockchain.

Use `api.query.treasuryBuyoutExtension.allowedCurrencies.entries()` to fetch allowed currencies.
Use `api.query.assetRegistry.metadata(...)` to fetch allowed currencies metadata.
Use `api.query.assetRegistry.metadata('Native')` to fetch native currency.

**Comment by ebma** [comment]
Nice ticket, thanks for creating it @Sharqiewicz 👌
