### ISSUE TITLE
Fix the calculation of the security deposit amount

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/portal#416]
## Problem

At the moment, the security deposit request to the user is 0.5% of the absolute amount of the asset being bridged. Since the griefing collateral is denoted in a different currency than the wrapped asset being bridged, we first have to convert the amount of the wrapped asset to the respective amount of the griefing-collateral currency with equivalent USD value.

## TODO

We need to change the calculation of the griefing collateral [here](https://github.com/pendulum-chain/portal/blob/34b48c34c182f81677da2dc8a01024e7acbae957/src/pages/bridge/FeeBox.tsx#L42C9-L44). What we need to do is:
- Convert the `amount` (of the wrapped asset, ie the user input) to its USD value by multiplying it with the price of that asset. This price should be available from the [usePriceFetcher](https://github.com/pendulum-chain/portal/blob/34b48c34c182f81677da2dc8a01024e7acbae957/src/hooks/usePriceFetcher.ts#L181) hook
- Convert the USD value result that we calculated in the previous step to the equivalent amount of the griefing collateral currency. The griefing collateral currency is exposed by the `useFeePallet` hook, see [here](https://github.com/pendulum-chain/portal/blob/34b48c34c182f81677da2dc8a01024e7acbae957/src/hooks/spacewalk/useFeePallet.tsx#L104). We again retrieve the price for that asset from the [usePriceFetcher](https://github.com/pendulum-chain/portal/blob/34b48c34c182f81677da2dc8a01024e7acbae957/src/hooks/usePriceFetcher.ts#L181) hook but this time, we have to divide the USD amount by the price. This is because all prices are denoted as 'asset' -> 'USD', thus we have to invert it for this calculation. 

The calculation can be simplified to
```
griefingCollateral =  amountWrapped * wrappedAssetPrice / griefingCollateralAssetPrice
```

We should use the BigNumber package to increase the precision of these calculations.

**Comment by Sharqiewicz** [comment]
Is somewhere defined the security deposit of 0.5% or should I hardcode it? @ebma 
Also if the security deposit is 0.5% would the calculation be `amountWrapped * wrappedAssetPrice * 0.05 / griefingCollateralAssetPrice` ?

**Comment by Sharqiewicz** [comment]
I have checkout from the GET PEN branch to implement this task as at that branch there is usePriceFetcher refactored

**Comment by ebma** [comment]
Yes, the 0.5% are basically denoted by [this](https://github.com/pendulum-chain/portal/blob/9bd53857c1a3198fa117b74ee1b4e6bd6d1331a4/src/pages/bridge/Issue/index.tsx#L49) fee so there is no need to hardcode it. You are right that it should be
```
securityDeposit =  amountWrapped * wrappedAssetPrice * issueGriefingCollateralFee (in percent) / griefingCollateralAssetPrice
```

I think we should rename [these](https://github.com/pendulum-chain/portal/blob/9bd53857c1a3198fa117b74ee1b4e6bd6d1331a4/src/hooks/spacewalk/useFeePallet.tsx#L13-L14) two variables to have a 'Fee' in the name.

**Comment by Sharqiewicz** [comment]
@ebma Thanks for explaining, I changed the code. I've spotted that `issueGriefingCollateralFee` is `0.005` instead of `0.05`

**Comment by ebma** [comment]
Oh right, it's 0.5% and not 5%. Sorry for the confusion.
