### ISSUE TITLE
Update error message for insufficient security deposit

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#417]
### Context
Currently, when the user doesn't have enough PEN to cover the requested security deposit, they see the message: 'You don't have enough balance to cover the deposit fees. 

### Requirement
- [ ] the ticket error message should be: `Insufficient PEN to cover the security deposit.`

<img width="699" alt="Screenshot 2024-04-19 at 13 00 09" src="https://github.com/pendulum-chain/portal/assets/138758794/11c300e5-1612-44cd-a2b6-c2c21518bf0c">

### Note
* Make the same changes to the Amplitude version and replace the PEN as AMPE in the text

**Comment by vadaynujra** [comment]
@annatekl what is pending on this one to be moved to Ready?

**Comment by annatekl** [comment]
this can be moved to ready @vadaynujra

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/417?planning-poker) with Zenhub @ebma @Sharqiewicz
