### ISSUE TITLE
Add new tokens to the dashboard 

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#419]
As a user i should be able to see the balances, price and its USD value of USDC, GLMR and HDX on the portal dashboard

## Acceptance Criteria
* On /dashboard
* Show GLMR, USDC and HDX
* Dashboard should show the wallet balances of those tokens along with price and its USD value

## Note 
* Here is the metadata of those tokens
* GLMR
    * Assetid - XCM: 6
    * Decimal - 18
    * Symbol - GLMR
    * Icons - https://drive.google.com/file/d/1ZU7rPWxBVP0sEDgJpZxr07eJm1cNyFz6/view?usp=drive_link
* HDX
    * AssetId - XCM: 8
    * Decimal - 12
    * Symbol - HDX
    * Icons - https://drive.google.com/file/d/1E3WzIWNW-4D5Y1f1AoxpPIe8E5wyV1wY/view?usp=drive_link
* USDC
    * AssetId - XCM:2
    * Decimal - 6
    * Symbol - USDC   
    * Icons - https://drive.google.com/file/d/1eChgTiNnGfwFr1sRLS4g1hkodIZCoGv-/view?usp=drive_link

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/419?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by Sharqiewicz** [comment]
It is really quick to do when #277 is merged. Only adding icons is left - 15 minutes. @prayagd

**Comment by Sharqiewicz** [comment]
The DIA Oracle doesn't cover all of the tokens. Additional fetching of token prices also to be implemented.

**Comment by Sharqiewicz** [comment]
@prayagd yes
