### ISSUE TITLE
Add fund wallet option to the Portal

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#421]
## Context
Currently all the PEN and AMPE buying and exchanging options are not clubbed and not very clear to the end user in attempt to fix that, this ticket aims at clubbing them under the "Fund wallet" feature where the user would get option to buy or exchange PEN and AMPE tokens

As a portal user, i should be able to buy or exchange PEN and AMPE using the Fund wallet option

## Acceptance criteria
* Remove "Zenlink AMM" option from Pendulum and Amplitude menu
* Remove "Buy PEN" option from Pendulum menu
* Show "Fund wallet" option in the side menu for both Pendulum and Amplitude with the icon given in the design, this feature should be available on the /fund url
* on clicking the option show on the screen two options "Buy" and "Exchange"
* Under "Buy"
    * For Pendulum show Alchemy Pay
    * For Amplitude show nothing
* Under "Exchange"
    * For Pendulum show Zenlink, Stellaswap and MEXC
    * For Amplitude show Zenlink
* Clicking on any of the above options should redirect to the respective onramps or exchanges, links are provided in the note section below
* User should be able to switch between Buy and Exchange fields
* Show redirect icons on each item under "Buy" and "Exchange"
* Please follow the same text provided in the design for Pendulum, text for "Buy" section Amplitude is "Currently no options available, Try Exchange!"

## Design
Pendulum - https://www.figma.com/proto/5up5sghcttBogehUq4255i/App?node-id=4054-757&t=BaiSFdnImuUIHPSI-0&scaling=min-zoom&content-scaling=fixed&page-id=3979%3A1234&starting-point-node-id=4054%3A757&show-proto-sidebar=1
Amplitude - https://www.figma.com/proto/5up5sghcttBogehUq4255i/App?node-id=4053-522&t=BaiSFdnImuUIHPSI-0&scaling=min-zoom&content-scaling=fixed&page-id=3979%3A1234&starting-point-node-id=4053%3A522&show-proto-sidebar=1

### Note
* Zenlink - https://app.zenlink.pro/swap
* Stellaswap - https://app.stellaswap.com/exchange/swap
* MEXC - https://www.mexc.com/exchange/PEN_USDT
* Alchemy Pay - Redirect link for Alchemy Pay

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/421?planning-poker) with Zenhub @ebma @Sharqiewicz @TorstenStueber

**Comment by ebma** [comment]
When are you going to provide the text for Amplitude?

**Comment by prayagd** [comment]
Will do it by EOD @ebma

**Comment by prayagd** [comment]
> Which day did you refer to? 😅 I think it's still not updated in the figma.

Its Today, hahaha. Sorry lost track of it, updated it now

**Comment by prayagd** [comment]
Add a link to Banxa

**Comment by TorstenStueber** [comment]
@prayagd I can't access the design. Can we generally give access to designs for all @pendulum-chain/devs members?

**Comment by prayagd** [comment]
> @prayagd I can't access the design. Can we generally give access to designs for all @pendulum-chain/devs members?

It was shared with Kacper and Marcel, Please request access if you havent got in future
