### ISSUE TITLE
Rename transfers to transactions for Spacewalk

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#427]
#### Context
We've noticed some confusion among users regarding the current subpage names under Spacewalk, namely 'Bridge' and 'Transfers.' Users seem to associate 'Transfers' with the bridging activity, which isn't the intended understanding. To address this, we propose renaming the subpage to 'Transactions' for clarity.

#### Requirements
- [ ] `Transfers` to be renamed to `Transactions`

**Comment by prayagd** [comment]
@annatekl where is this coming from? it was first txn history only before changing it to transfers and now we want to change it back?

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/427?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by vadaynujra** [comment]
@prayagd this was feedback from the user interview sessions we've been running, followed by a poll from the team.
