### ISSUE TITLE
Remove the security deposit from the "to stellar" UI

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#438]
As a spacewalk bridge user, i should not be able to see security deposit on the "to stellar" window

## Acceptance criteris
* on /spacewalk
* Navigate to "to stellar" option
* In the fee breakdown, dont show "Security Deposit"

### Note
* There is no security deposit while bridging back to stellar.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/438?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by annatekl** [comment]
@ebma can you please fix that
