### ISSUE TITLE
Portal dashboard - Add prices for assets, update filter to dashboard

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#439]
As a portal user, I should see prices for all the tokens displayed on the dashboard, also the filters should work properly 

## Acceptance criteria
* Add a default filter to the portal dashboard based on the **USD value** of the tokens, from descending to ascending
* Add prices for following assets on Pendulum
    * HDX - https://www.coingecko.com/en/coins/hydration
    * ASTR - https://www.coingecko.com/en/coins/astar
    * BNC - https://www.coingecko.com/en/coins/bifrost-native-coin
    * PDEX - https://www.coingecko.com/en/coins/polkadex
*  Add prices for following assets on Amplitude
    * PICA - https://www.coingecko.com/en/coins/picasso
* The filters for the column should work for only two combinations i.e descending to ascending and vice versa and not other combination, currently it works for three combination where the third combination is unclear

## Note
* Prices for PINK are missing on coingecko, so we dont add it for now
* EQD is to be unregistered so no price for that

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/439?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by prayagd** [comment]
@ebma @Sharqiewicz I have updated the description of the ticket, please have a look and let me know if any questions.

**Comment by ebma** [comment]
As far as I know we want to discontinue the support for EQD anyway since the chain is dead. Regarding PINK, I'm not sure but I'd rather prefer if we don't show a price for it as long as it's not available on Coingecko. Adding yet another extra handling just for that wouldn't be worth it IMO.

@Sharqiewicz if you happen to work on this ticket, please reach out to me for the API key.

**Comment by prayagd** [comment]
> As far as I know we want to discontinue the support for EQD anyway since the chain is dead. Regarding PINK, I'm not sure but I'd rather prefer if we don't show a price for it as long as it's not available on Coingecko. Adding yet another extra handling just for that wouldn't be worth it IMO.

Ok, makes sense

**Comment by Sharqiewicz** [comment]
@prayagd @vadaynujra Blocked until https://github.com/pendulum-chain/oracle-pallet/issues/27 is resolved.
