### ISSUE TITLE
Rename the text for Insufficient Balance for Deposit Fees

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#440]
#### Context
Currently if the user is not having any PEN to cover the security deposit the error message is: 'You don't have enough balance to pay the deposit fees.' We want to change the text so is understandable to the user that the security deposit fees are paid in PEN token. 
<img width="573" alt="Screenshot 2024-05-06 at 10 04 52" src="https://github.com/pendulum-chain/portal/assets/138758794/a18e68f5-302a-490f-9ac7-fb9735188a44">

#### Requirement
- [ ] Change the error message to: Insufficient PEN balance to pay the deposit fees.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/440?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by ebma** [comment]
Isn't this ticket a duplicate to #417.

**Comment by annatekl** [comment]
yes it is. closing as duplicate to https://github.com/pendulum-chain/portal/issues/417.
