### ISSUE TITLE
Cannot connect Nova wallet from mobile browser

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#449]
### Describe the bug

User not able to connect to Nova wallet from the mobile browser

### Reproduction

1. open [portal.pendulum.org](http://portal.pendulum.org/)
2. Click on wallet connect, trying locally with nova (failed 3 times)

### Expected behavior

Fetch the Nova wallet details or redirect to the Internal Nova wallet broswer when Nova wallet selected

### Smartphone (please complete the following information):

- Device: iPhone
- Browser: Safari

### Additional coments

* User managed to connect the wallet in the 4th Attempt, to face one more error in the Spacewalk bridge menu was unable to select the tokens to Bridge.

**Comment by Sharqiewicz** [comment]
Tested on Safari and Chrome with iPhone 14 Pro and everything works perfectly for Pendulum, Amplitude and Foucoco. @prayagd

**Comment by Sharqiewicz** [comment]
Resolving this issue in the ticket #28
https://app.zenhub.com/workspaces/pendulum-6408a0365cda59c57d39bee5/issues/gh/pendulum-chain/portal/28

**Comment by Sharqiewicz** [comment]
@prayagd Can be tested now. I tested it in Nova app on my iPhone and it works

**Comment by prayagd** [comment]
@Sharqiewicz tested on my end too on andriod, works perfectly also in normal browser it is redirected to nova website. So all good.

**Comment by prayagd** [comment]
We can close if changes are merged
