### ISSUE TITLE
Update design/branding of collator list

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#45]
As a portal user, I must be able to see the collator list with new branding/design

# Acceptance criteria
* Show two containers on the top of the collator list page
   * one for collator balance and undelegation time
   * other for claiming staking rewards
* Below these containers show the collator list with following headings
   * Collator
   * Total staked
   * Delegators
   * APY
   * My staked
* All designs/branding can be found in the wireframe attached below. 

# Wireframe
https://www.figma.com/file/XLIKffEYnK9autHMM1YgA3/Flows?node-id=86%3A299&t=wC9J2NkPZrSzvaHO-4

**Comment by prayagd** [comment]
@gonzamontiel Here is the new ticket for updating the branding/design of the collator list. Let me know if anything unclear. Thank you 🙏🏻

**Comment by gonzamontiel** [comment]
![Screenshot from 2023-02-22 13-10-15](https://user-images.githubusercontent.com/4713407/220616334-2d549dad-80bf-4955-bddb-a700d6a6cea2.png)
@prayagd what is "AMPE unboarding" ? Is that a button? What would be the action?

**Comment by prayagd** [comment]
@gonzamontiel No that's not a button it just a thing to show AMPE that are in cool-off period after undelegation.

**Comment by gonzamontiel** [comment]
Oki. Another one. "My Staking" would be the sum of all the staking in different collators BUT, afaik, you can only delegate to one. So this number would be the same that the user will observe in one of the collator rows. Is that okay?

**Comment by prayagd** [comment]
@gonzamontiel You are right, we developed this when Kilt did not remove the functionality of delegate to one. As of now we can go ahead with this as both the numbers in the column and under "My Staking" would be same.
