### ISSUE TITLE
Resize the token view on the dashboard

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#454]
## Context
There is empty space below the token view on dashboard, which can be utilitized to show more tokens in a single view

## Requirment
* Increase the size of the token view component below to occupy the empty space on dashboard

## Reference
<img width="1138" alt="Screenshot 2024-05-17 at 5 55 43 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/91416de9-9a29-4fd6-a1e6-edbaab961353">

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/454?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by prayagd** [comment]
moving to development, as this is been worked upon in the GET PEN PR right @Sharqiewicz ?

**Comment by ebma** [comment]
The dashboard now shows 8 rows instead of just 5 on production. Should we close this ticket @prayagd?

**Comment by Sharqiewicz** [comment]
@ebma yes

**Comment by prayagd** [comment]
Yes closing as this was addressed in the GET PEN PR
