### ISSUE TITLE
Update the disclaimer for Amplitude Spacewalk

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#458]
## Context

Now that the issue and redeem fee is updated, the disclaimer text is outdated and needs to be updated. Change to be made only on Amplitude network.

## Requirement

- [x] Disclaimer should be renamed to Bridge Terms.
- [x]  Bridge Terms:
- Bridge Fee: 0.1% of total bridging amount.
- Security Deposit: 0.5% of the transaction amount in AMPE, refunded after successful bridging.
- Estimated Time: Within a minute after submitting the Stellar transaction. Contact support if your transaction is still pending after 10 minutes.
- [x] The contact support link should be updated to point directly to the Discord #get-help [channel](https://discord.com/channels/841944723979108403/1247164487883292672).*

* Note for New Users: Upon clicking the support link, new users will be directed to the verification process on Discord. After successful verification, they will need to manually navigate to the #get-help channel for assistance.

**Comment by vadaynujra** [comment]
@annatekl can you update the description based on what we discussed today? @prayagd we are completely revamping the `Disclaimer` section.

**Comment by annatekl** [comment]
Do you think we need this sentence in our disclaimer 'Join our vault operator program, more here.' @prayagd

**Comment by vadaynujra** [comment]
Since it is `Join our vault operator program, more here.` is not a 'Disclaimer', I would say no. 
I also don't think the rest of the information we're sharing there is a 'Disclaimer'. Do you agree @annatekl ? If yes, what could be a better heading for this section?

**Comment by vadaynujra** [comment]
Also, please confirm in a commnent when the description of the ticket has been updated @annatekl

**Comment by annatekl** [comment]
updated @vadaynujra

**Comment by annatekl** [comment]
text changed @vadaynujra

**Comment by vadaynujra** [comment]
@annatekl how about calling the heading Details i.e. changing Disclaimer to Details?

**Comment by vadaynujra** [comment]
Estimated time for issuing to just 'Time'?

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/458?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by annatekl** [comment]
@vadaynujra any comments? changes as per the latest comment from Liam

**Comment by annatekl** [comment]
@vadaynujra discussed with marketing that estimated time sounds better
