### ISSUE TITLE
Update the disclaimer for Pendulum Spacewalk

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#459]
## Context
The disclaimer text is outdated and needs to be updated. Change to be made only on Pendulum network.

#### Requirements
- [x] Disclaimer should be renamed to **Bridge Terms**
- [x] Bridge Terms: 
- Bridge Fee: Enjoy zero fees now, 0.1% coming soon.
- Security Deposit: 0.5% of the transaction amount in PEN, refunded after successful bridging.
- Estimated Time: Within a minute after submitting the Stellar transaction. Contact support if your transaction is still pending after 10 minutes.
- [x] The contact support link should be updated to point directly to the Discord #get-help [channel](https://discord.com/channels/841944723979108403/1247164487883292672). *

* Note for New Users: Upon clicking the support link, new users will be directed to the verification process on Discord. After successful verification, they will need to manually navigate to the #get-help channel for assistance.

**Comment by annatekl** [comment]
@vadaynujra looks completed now

**Comment by vadaynujra** [comment]
@annatekl instead of writing what to remove, can we just write the acceptance criteria? What should we see in this section altogether?

**Comment by vadaynujra** [comment]
Also let's not have completely different versions of texts for Amplitude and Pendulum, just the bits that are necessarily different e.g. limits, fees.

**Comment by annatekl** [comment]
updated the disclaimer text

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/459?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by annatekl** [comment]
@vadaynujra any comments? changes as per the latest comment from Liam

**Comment by vadaynujra** [comment]
@annatekl if this disclaimer text is only for the issuance, then can we remove the 'for issuing' after estimated time?

**Comment by vadaynujra** [comment]
Also can you please ensure there are no typos in the Ready ticket? See `requirements` and `disclaimer`

**Comment by annatekl** [comment]
ticket updated @vadaynujra

**Comment by vadaynujra** [comment]
> For users who are not verified yet, they should be redirected to #get-help after completing the verification process.

Not entirely sure if this is possible (or too complex to implement). So we can be flexible here for users who aren't already part of the Discord server that they first verify themselves and then click on the link the second time would send them to the specific #get-help channel.

**Comment by annatekl** [comment]
After email and phone verification, the user is redirected to the general chat. Is it more complex to redirect them to the help section after verification, @ebma? If so, we can keep them in the general chat. If the user clicks the link a second time, they can be redirected to the get-help section.

**Comment by ebma** [comment]
> After email and phone verification, the user is redirected to the general chat. Is it more complex to redirect them to the help section after verification, @ebma? 

I think we can't influence that redirection if this is the case. Seems to be a limitation by Discord then.

**Comment by vadaynujra** [comment]
@annatekl please update the ticket to reflect that we don't redirect user to get help for new users. 
@Sharqiewicz I also made some changes to the text (added `PEN`), so please consider that when working this issue.

**Comment by prayagd** [comment]
@Sharqiewicz i guess this was wrongly closed, the changes described in the ticket are not live

**Comment by annatekl** [comment]
@Sharqiewicz when this can be merged? Shall we also progress with the changes for the [ticket](thttps://app.zenhub.com/workspaces/pendulum-6408a0365cda59c57d39bee5/issues/gh/pendulum-chain/portal/458)

**Comment by Sharqiewicz** [comment]
@annatekl There are other priorities right now. Once I finish them, I'll take care of this ticket. For now I move it to the Ready column.

**Comment by ebma** [comment]
I took over this ticket because fixing both Amplitude and Pendulum in the same PR was easiest.

**Comment by prayagd** [comment]
> Within a minute after submitting the Stellar transaction

@annatekl did you mean wWait a minute instead of within? because the sentence does not makes sense
