### ISSUE TITLE
Rename the assets on Nabla foucoco deployment

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#465]
## Context
Currently the assets on the Nabla foucoco deployment are named randomly, marketing has requested to change the names on the UI for the testnet campaign of Nabla.

## Requirement
* Change "NAT" ticker to "AMPE" and name to Mock Amplitude
* Change "X0" ticker to "USDC" and name to Mock USDC
* Change "X1" ticket to "BRL" and name to Mock BRL
* Change "X2" ticket to "EURC" and name to Mock EUR
* Change "X3" ticket to "USDT" and name to Mock USDT

## Note
* Changes are to be made to the UI on Foucoco

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/465?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by TorstenStueber** [comment]
This requires a new deployment of Nabla itself. Please make this a task ticket instead.

Background: the names come from the smart contracts, I would not like to add code to the Portal to override these names.

**Comment by TorstenStueber** [comment]
@prayagd Something that is not specified here is the name and symbol of the LP tokens. I will use the same pattern as for the prototype deployment on Pendulum, e.g., name: EURC Swap LP, symbol: EURC-LP.

**Comment by TorstenStueber** [comment]
I redeployed the contracts. They are now at the following addresses:
* router: `6h54SUQjbXjYbYT7p7vDcXSVGAQNgu78jkhErLJoW7EXo3ry`
* ERC20 wrapper for AMPE: `6iijkH7hefUhRzfUgHHn262VuoLfhum9HQwxmFAmXsKRpSQf`
* ERC20 wrapper for USDC: `6hS3ArenXj2mmPjqJpMyf8YukcayWp8MfiSZC551mfYxWe38`
* ERC20 wrapper for BRL: `6jRPmndEpBLEveSFu7YcfaD4JgaWJDWEUWvhfzKRpUJqHya3`
* ERC20 wrapper for EURC: `6hxvhYubaSAxcaB8muaX8HWjyGccJLJaTnvc9gtyLjx89bne`
* ERC20 wrapper for USDT: `6iQdyawyTbqTAhfiiiUW8ktG9ph86n5ygm4jYoDAhvE2xTBd`
* priceFeedWrapper: `6nT6THovpSsTtCCi9Lae1NoAAviLbzULaEo41Yg5eYJrCZXu`
* nablaCurve: `6h8ibcsVi75MFgZ9csAL4kmr3TX1e63V8HVL298rVxEJVhZT`
* backstop: `6jqj7JYKAJuVZJrodgY1Ha3JUf2JVVCBeYG1915GJaVLxBsB`
* swap pool for AMPE: `6kzUyLB9JUBzhKFi8PVBWPq5yJh7EHVsydPWEPitD9CVxcg5`
* swap pool for USDC: `6jgftzKfwcE76vtm6GyXp13qzRgWctc6tXxNFNoorKLPRvAe`
* swap pool for BRL: `6mExNrhAS7nTdwRo6iismCyoLxtYivPHKxQkYvMLrL9j6zmr`
* swap pool for EURC: `6hH1kHZZtpkczSxyRq9RLe3UhLXqRGf3koeqwH6ka9o8sF1C`
* swap pool for USDT: `6msKtupHnRd7iZHtzgQUFUeFG35bxEqGNEdkLnNUg8Vbvuhj`

**Comment by TorstenStueber** [comment]
Now that this is done, we would need to deposit some liquidity to this new Nabla instance. I will go ahead and do just that.

**Comment by TorstenStueber** [comment]
I added 10K tokens to each pool, including backstop pool.

**Comment by prayagd** [comment]
@TorstenStueber The newly deployed AMPE != AMPE on foucoco? I have AMPE balance still its shows N/A on swap UI. See screenshot
<img width="907" alt="Screenshot 2024-05-30 at 10 47 45 AM" src="https://github.com/pendulum-chain/portal/assets/52105313/b11a9432-5050-4915-9ecd-ffc6f85f58b0">

**Comment by TorstenStueber** [comment]
That's curious. Let me check.
