### ISSUE TITLE
Add a arrow to reverse the swap on the swap UI of forex AMM

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#466]
## Context
As a user i should be able to reverse the direction of swap on the Forex AMM swap UI

## Requirement
* Show a arrow icon between the source input field and destination input field
* Clicking on the arrow icon should reverse the swap i.e source should become destination as vice versa
* When reversing change both the assets and the amount that are entered

## Note
* Here is the arrow icon -> https://www.figma.com/design/5up5sghcttBogehUq4255i/App?node-id=609-702&t=MvishhshllbVqnge-0
* Reference for position of the arrow icon -> https://www.figma.com/proto/5up5sghcttBogehUq4255i/App?page-id=1687%3A1028&node-id=4873-3650&viewport=-3151%2C1567%2C0.4&t=pK7xJWGjzNSoQQeV-1&scaling=min-zoom&starting-point-node-id=4873%3A3650

**Comment by prayagd** [comment]
Will add the arrow icon as i get it from Klaus

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/466?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by prayagd** [comment]
@prayagd to add a video of the uniswap reference

**Comment by TorstenStueber** [comment]
This is already implicitly possible by just selecteding the "To" asset as the "From" asset (or vice versa). In this case the UI will just swap both assets (instead of having equal "To" and "From" assets).

**Comment by prayagd** [comment]
> This is already implicitly possible by just selecteding the "To" asset as the "From" asset (or vice versa). In this case the UI will just swap both assets (instead of having equal "To" and "From" assets).

That is not intuitive @TorstenStueber Most people who use dex are used to the arrow funtionality
