### ISSUE TITLE
Show BSP and swap balance 0 when wallet not connected

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#469]
### Describe the bug
Currently when the wallet is not connected to the portal, the swap UI and the BSP UI loads continuously showing a animation

### Reproduction

1. Go to https://portal.pendulumchain.org/foucoco/nabla/backstop-pools
2. See the loading animation
3. Same applies for the swap UI, the balances component also keeps loading

### Expected behavior
Nothing should be displayed as the wallet is not connected to the Portal UI

### Screenshots
<img width="944" alt="Screenshot 2024-05-28 at 4 02 49 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/2d5f2f5c-7c47-441f-946d-ecc9fe9dc735">
<img width="671" alt="Screenshot 2024-05-28 at 4 03 01 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/79900795-d501-4ce6-98da-8155836b035c">

### Desktop (please complete the following information):

- OS: MacOS
- Browser: Chrome, Firefox

**Comment by TorstenStueber** [comment]
This is not a bug in my opinion. If there is no wallet connected, I think also 0 is just wrong and could be potentially confusing – at least for me. There is just no meaningful number.

I would show some UI instead that indicates to "connect a wallet".

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/469?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by prayagd** [comment]
@TorstenStueber based on your response, i checked the uniswap UI. They prefer to show nothing, i think so that too works instead of the constant loading block
