### ISSUE TITLE
Add link to subscan explore on the transaction status pop-up

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#471]
## Context
Currently if the swap txn executed by the user is successful or failed on-chain only the status of that is displayed on the pop-up. There is no link to the explorer. 

## Requirment
* Once the user initiates the swap transaction
* If the txn is successful on-chain
    * Add a link to the subscan transaction on the Transaction successful pop-up with text "View on Explorer" above the close button
* If the txn is fails on-chain
    * Add a link to the subscan transaction on the Transaction failed pop-up with text "View on Explorer" above the close button
 
## Note
* This is only for Pendulum
* Reference of the pop-up
![image](https://github.com/pendulum-chain/portal/assets/52105313/62b9c092-a46e-4ec8-9ed2-60f784773d49)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/471?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by prayagd** [comment]
@TorstenStueber: ensure that the api-solang library returns that info

**Comment by TorstenStueber** [comment]
Why is this ticket considered blocked? Because it only applies to Pendulum?

**Comment by prayagd** [comment]
Yes, it is possible to ship this even though the Pendulum deployment is not live?

**Comment by Sharqiewicz** [comment]
@prayagd  I think we can make the code so that it works when the Pendulum implementation is live. I'll remove the Blocked label

**Comment by prayagd** [comment]
@ebma can we pick this one?

**Comment by ebma** [comment]
Sure @prayagd, I'll give it a shot
