### ISSUE TITLE
Deposit screen does not closes after successful deposit

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#472]
### Describe the bug
After a user successfully deposits asset into the swap pool, the user still sees the Deposit pop-up after the successful confirmation pop-up is closed [see screenshot]

### Reproduction

1. Go to https://portal.pendulumchain.org/foucoco/nabla/swap-pools
2. Deposit any asset, after successfully depositing and closing the "Transaction successful" pop-up
3. User still sees the asset deposit screen

### Expected behavior
After the successful deposit the asset deposit screen should go away the user should only see the swap-pool screen

### Screenshots
<img width="1148" alt="Screenshot 2024-05-28 at 6 20 28 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/8a251fa6-fca3-443a-9bdb-c1ecfb414126">

### Desktop (please complete the following information):

- OS: MacOS
- Browser: Chrome

**Comment by TorstenStueber** [comment]
This is not a bug. It's just implemented that way (there was no real spec).
