### ISSUE TITLE
Text changes on the Nabla swap screen

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#473]
## Context
This ticket is to fix inconsistencies across the swap UI

## Requirement
* Remove "Your" from "Your Balance" from the UI inputs fields 
* Change to "Balance" in the destination input field
* From "Your Balance: 22 X0", remove the token name i.e XO

## Reference
<img width="605" alt="Screenshot 2024-05-28 at 6 27 08 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/f81c7d9a-8807-4f74-954d-40d9fcafac0b">

**Comment by TorstenStueber** [comment]
I added "your" on purpose. Before that it was never clear in the UI what balances and amounts apply to you or to the pool in general (e.g., is this a pool balance).

The UI is full of different numbers and I feel this is quite overwhelming to users (particularly if they are not numbers affine).

I suggest that we make it dead obvious what the numbers mean, e.g.:
* is it an amount that I have
* is it an amount that I will receive or pay as an outcome of this action
* is it my new resulting balance after the transaction
* is it a total amount that takes all users into account (e.g., a pool balance)
etc.

There are so many ways what a number can mean on the UI and we should not make the user guess.

**Comment by prayagd** [comment]
<img width="606" alt="Screenshot 2024-05-29 at 11 53 24 AM" src="https://github.com/pendulum-chain/portal/assets/52105313/5d26eee8-27ee-4fec-9f11-2a7fcff2764c">

@TorstenStueber above is the screenshot of uniswap screen, leading DEX in the entire crypto ecosystem. Do you find this confusing too? The attempt here is to make familiar to the general DEX UI. 

> I added "your" on purpose. Before that it was never clear in the UI what balances and amounts apply to you or to the pool in general (e.g., is this a pool balance).

Sorry dont agree, i dont think so any user on the swap screen would confuse the balance as pool balance.

**Comment by TorstenStueber** [comment]
Yes, I find this confusing. Why would it be clear that this is not the pool balance, which is equally reasonable?

If every new project just copies what already exists, disruption would never be possible. But that's just my opinion. Happy to support a change if this a fringe opinion.
