### ISSUE TITLE
Add icons to the assets on the Portal for Amplitude and Pendulum

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#488]
#### Context 
Our current dashboard displays icons for assets that are listed in our asset registry. However, not all assets currently have corresponding icons. To improve the user experience and maintain visual consistency across the dashboard, we need to create icons for the assets that are missing them.

Assets where icons are missing Pendulum: PINK, HDX, ASTR, BRZ, EQD, PDEX
Assets where icons are missing Amplitude: PICA

#### SVG files
[here](https://drive.google.com/drive/u/0/folders/1sZcQzoDxT_EUd2wtEJN8ECNzPakfAMs6)

#### Requirements
- [ ] add Icons to the the assets on Dashboard view

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/488?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by Sharqiewicz** [comment]
Wait for #495

**Comment by ebma** [comment]
#495 is merged and this should be unblocked 👍
