### ISSUE TITLE
Show portfolio on Dashboard

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#49]
As a AMPE holder, i should be able to see the AMPE balance in my wallet on the dashboard

# Acceptance criteria
* on /dashboard
* If the wallet is connected show AMPE balance on the dashboard. 

# Note
* This functionality was present before the rebranding.

**Comment by prayagd** [comment]
@ebma Can you please confirm when this is live. Users would also be able to see $PEN balance. Right?

**Comment by ebma** [comment]
I'm not sure I understand the question. Is is about seeing the dollar price representation? Or is it about seeing the PEN token balance?

**Comment by prayagd** [comment]
@ebma PEN token balance.

**Comment by ebma** [comment]
Yes we can show the PEN token balance once the chain is live.

**Comment by prayagd** [comment]
@gonzamontiel I hope its ok if i move this to done.
