### ISSUE TITLE
Disable bridge if user doesn't have enough security deposit

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/portal#501]
### Context
Currently on Spacewalk, when a user wants to bridge an amount to Pendulum, which requires more of the native token than their transferable balance, they are able to sign the transaction, and then shown an error

### Requirement
- [ ] Disable the bridge button when the user's native token balance (PEN or AMPE) is lower than the security deposit required for the amount they want to bridge.
- [ ] Display the error message 'Insufficient PEN for gas and security deposit' when the user's native token balance (PEN or AMPE) is lower than the security deposit required for the amount they want to bridge.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/501?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by ebma** [comment]
This will be fixed in https://github.com/pendulum-chain/portal/pull/436 but it has not yet been reviewed by a member of the product team.

**Comment by vadaynujra** [comment]
Great. Can be completed much quicker in that case.

**Comment by ebma** [comment]
We recently merged #436, can you please test on production and let me know if the current state is enough? Then we can close this ticket.

**Comment by vadaynujra** [comment]
![Screenshot_20240627-174351.png](https://github.com/pendulum-chain/portal/assets/98896595/b2105a29-6f66-44c0-9b2a-e6549c1e7981)

Looks good and can be closed @ebma
