### ISSUE TITLE
Bridge back to stellar - max amount chosen by the user allow for the amount that is incompatible

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#503]
#### Context
When choosing 'Back to Stellar' and entering 'Max,' the amount prefilled by the system is half the available funds and correct, but the error message after the transaction is signed indicates that the amount is incompatible.

#### Reproduction
Steps to reproduce the behaviour:

1. Go to the Spacewalk bridge.
2. Click on "Back to Stellar."
3. Click on 'Max' to prefill the maximum available amount.
4. Sign the transaction.
5. See error message: "Transaction failed with errors: currency.Incompatible/Amount: The amount is incompatible."

#### Expected behavior
- [ ] The system should choose compatible amount when user clicks "Max" and the transaction should succeed.
- [ ] The system should prefill the maximum available amount with the correct decimal number limited to 7.

### Screenshots
<img width="438" alt="Screenshot 2024-06-25 at 15 47 59" src="https://github.com/pendulum-chain/portal/assets/138758794/cf55482e-daa4-426c-9712-05aaa287639a">

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/503?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by ebma** [comment]
@Sharqiewicz this should be an easy fix. We should simply now allow more than 7 decimals in that input field.

**Comment by annatekl** [comment]
ticket updated @ebma

**Comment by vadaynujra** [comment]
@annatekl can you add the other bugs found on the To `Stellar` flow into this ticket too?

**Comment by annatekl** [comment]
@ebma can we fix in this ticket:
- Redirect Issue: The "View in Progress" action is currently redirecting users to a "Not Found" page instead of the intended "Transactions" page.
- Error Message for Invalid Input: When a user enters 0, no error message is displayed. We expect an error message stating, "You need to enter a positive number."

**Comment by vadaynujra** [comment]
@annatekl the ticket has already been worked upon and [asked for a product review / test](https://satoshipay.slack.com/archives/C070VFD19B6/p1719346976306919?thread_ts=1719299063.014569&cid=C070VFD19B6) yesterday. Could you create new bug ticket for the additional bugs. If we want to get it included, it's best to include it in the ticket description before the tech team starts working on it.
