### ISSUE TITLE
Add Loading for Dashboard and GET PEN

### ISSUE THREAD

**Issue by Sharqiewicz** [pendulum-chain/portal#511]
### Describe the bug

When I am loading the portal (dashboard), it shows me a warning about insufficient funds to execute transactions. After loading this warning disappears, but because the loading takes quite a while, I am already concerned as a user, if someone hacked my PEN balance

### Reproduction

1. Go to Dashboard

### Expected behavior

My expectation as a user would be, that instead of showing a warning, I could see some info, that the portal is loading.

1. Show Skeleton component when Dashboard is loading
2. Show no GET PEN when the page is loading

**Comment by prayagd** [comment]
@Sharqiewicz can we close this ticket, i see a closed PR in this ticket?
