### ISSUE TITLE
Nabla - Page Refresh Required After Currency Swap

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#531]
After swapping one currency to another on the platform, users must refresh the page to initiate another swap. If they attempt a second swap without refreshing, they encounter the following error: "Transaction failed."

### Reproduction

1. Go to Nabla
2. Click on Swap (chosen currency AMPE to BRL)
3. Approve and execute the swap
4. Try to swap again
5. See error
<img width="609" alt="Screenshot 2024-07-26 at 11 53 40" src="https://github.com/user-attachments/assets/4f8cc8ac-3cf3-4350-b538-f513fb86915e">

### Expected behavior

Users should be able to perform multiple currency swaps consecutively without encountering errors.

**Comment by prayagd** [comment]
cc @Sharqiewicz @ebma

**Comment by ebma** [comment]
Let's do the effort estimates then?

**Comment by vadaynujra** [comment]
@ebma any reason to suggest estimating this 'bug'?

**Comment by Sharqiewicz** [comment]
@prayagd It is really difficult to debug when Foucoco is down. I think this should be picked up once Foucoco starts running.

**Comment by vadaynujra** [comment]
@Sharqiewicz can we work on this one now? or is Foucoco is still blocking?

**Comment by ebma** [comment]
It should be okay to test on Foucoco again. However, @Sharqiewicz if you try it out and encounter any weird issues, please reach out again. Since Foucoco was only partially moved to the new relay chain and we were not able to keep some of the contracts state, it might be that we need to deploy them again.

**Comment by TorstenStueber** [comment]
It is now possible to test as there is a working Nabla instance again. The previous Nabla instance was completely gone since we switched to Paseo. See https://github.com/pendulum-chain/portal/pull/579
