### ISSUE TITLE
Make new changes to the PEN onramp

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#536]
## Context
Alcehmy pay which is our offramp has made some changes to their api for security reasons, we need to update them as the have also impacted our default setup of showing PEN as a onramp option

## To-do
* Upgrade to a new signing method, sharing all the necessary links below
* When redirect from the portal, it should show PEN as offramp option and the fiat currency as per geographic location (In think so this is taken care by the api)

## Notes
- Page Integration Signing Instructions: (https://alchemypay.readme.io/v4.0.2/docs/ramp-signature-description)
- API Integration Signing Instructions: (https://alchemypay.readme.io/v4.0.2/docs/api-sign)
- Webhook Signing Instructions: (https://alchemypay.readme.io/v4.0.2/docs/webhook-signature)
- The new signing method requires the merchantOrderNo parameter to be mandatory and unique (non-repeating).
- The existing signing method will no longer be supported after August 15, 2024.

**Comment by prayagd** [comment]
as per my knowledge we have page integration

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/536?planning-poker) with Zenhub @ebma @Sharqiewicz @TorstenStueber

**Comment by prayagd** [comment]
incase production keys are required, please reach out to @prayagd will share them on slack

**Comment by TorstenStueber** [comment]
@Sharqiewicz what is the status of this ticket, is it still in development?

@prayagd what is the priority, is there any imposed deadline?

**Comment by Sharqiewicz** [comment]
@TorstenStueber In order to make it work we need a backend service. @ebma and @zoveress are working on setting up the service.
The url is not working for a long time now - instead of redirecting to AlchemyPay with PEN opened by default, it opens AlchemyPay with ACH opened by default, so there is no deadline as it is already not working

**Comment by ebma** [comment]
Yes, I'm still working on this but @zoveress and I at least managed to get the Lambda function that is supposed to sign the URL with a custom secret to work. The need for this extra backend made this task more difficult than it should be.
