### ISSUE TITLE
Wallet connection breaks when switching from Pendulum to any other network

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#541]
### Describe the bug
If a user switches the network from Pendulum to any of the other two networks and the wallet is connected then its diconnects and the user have to connect again, this happens only from Pendulum not for other networks

### Reproduction

1. Go to https://portal.pendulumchain.org/pendulum
2. Try switching network
3. See that the wallet connection breaks and the user have to connect again

### Expected behavior
The wallet should stay connected even when networks are switched

### Desktop (please complete the following information):

- OS: MacOS
- Browser: Chrome

**Comment by prayagd** [comment]
cc @Sharqiewicz @ebma

**Comment by ebma** [comment]
Why always the cc, just ask for the effort estimates @prayagd? 😅 Or are we not estimating bug tickets anymore? I forgot.

**Comment by prayagd** [comment]
sorry for the spam pings  🙈, we dont estimate bug tickets
