### ISSUE TITLE
Manual vault selection for Spacewalk on Pendulum not possible

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#553]
#### Bug Description
Manual vault selection for Spacewalk on Pendulum is not possible.

#### Steps to Reproduce
- Go to Spacewalk on Pendulum (Bridge to Pendulum and Stellar).
- Select any asset.
- Attempt to manually select a vault.
- Error: The chosen vault is not selected.

#### Expected Behavior
The user should be able to manually select different vaults.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/553?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by ebma** [comment]
@pendulum-chain/product I thought we don't estimate bug tickets?

**Comment by annatekl** [comment]
true, ok

**Comment by prayagd** [comment]
Removed the estimate
