### ISSUE TITLE
Improve Manual Vault Selection for Spacewalk (Amplitude and Pendulum)

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/portal#556]
#### Context
Now that we have multiple vaults for the same assets on Spacewalk, there's no clear indication for users that they can bridge larger amounts. The current portal view defaults to one vault (possibly chosen at random), displaying the max issuance based on that specific vault's capacity. This can lead to users with intentions of bridging higher amounts dropping off the flow, mistakenly believing that their request can't be accommodated.

#### Requirements
- [ ] By default, the vault with the highest issuance is selected
- [ ] add a tooltip text that appears when users mouse over the settings button. This text should be "Select Vault".

![image (17)](https://github.com/user-attachments/assets/84f4652e-71ae-42ea-b390-f30a6620f3e9)
![image (18)](https://github.com/user-attachments/assets/3e70078e-703f-46e1-9cf6-ce33c094628a)

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/556?planning-poker) with Zenhub @ebma @Sharqiewicz

**Comment by vadaynujra** [comment]
Needs to be detailed further @annatekl and then tech could estimate. Can also consider splitting this into 2 tickets one for the vault selection logic change and the other with the text changes.

**Comment by annatekl** [comment]
requirements adjusted @ebma

**Comment by vadaynujra** [comment]
@annatekl would be worth linking to the other ticket related to this one? IIRC that one about text changes should only be implemented once this one has been?
