### ISSUE TITLE
Change footer of Forex AMM subpages and correct Circle EURC icon

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#564]
## Context
This ticket is to make sure the public deployment of Forex AMM has the correct icons and the footer of all the subpages under Forex AMM should be changed

## Todo
* Set the correct icon for EURC circle, the icon is already available on the portal as it is enabled on the Portal dashboard
* Change the footer on all sub-pages to "Powered by Nabla technology" to "Powered by Vortex Finance"

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/564?planning-poker) with Zenhub @ebma @Sharqiewicz @TorstenStueber

**Comment by Sharqiewicz** [comment]
@prayagd All the changes are implemented here: https://github.com/pendulum-chain/portal/pull/557

**Comment by ebma** [comment]
Let's close this now that #557 is merged.
