### ISSUE TITLE
Show token symbols on swap pool UI

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#592]
As a Forex AMM user, i should be able to see token symbols on the swap pool UI

## Acceptance criteria
* Replace the token names with the following symbols in the "Name" column. To do this, change the implementation to display the value of the `symbol` field instead of the `name` field of each token.
    * DOT
    * USDC
    * EUR.s
    * USDC.axl
* The name column is already getting renamed in this [ticket](https://github.com/pendulum-chain/portal/issues/474)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/592?planning-poker) with Zenhub @ebma @Sharqiewicz @TorstenStueber

**Comment by TorstenStueber** [comment]
As mentioned by @ebma we can close this ticket here once https://github.com/pendulum-chain/portal/pull/565#pullrequestreview-2389400698 is merged.
