### ISSUE TITLE
Migrate from Preact to React

### ISSUE THREAD

**Issue by Sharqiewicz** [pendulum-chain/portal#596]
Given the growing feature gaps and long-term advantages of React over Preact, we have decided to migrate the application from Preact to React

Todo:
- [ ] Replace Preact with React dependencies.
- [ ] Update all components and ensure compatibility with React. (If needed implement concurrency)
- [ ] Refactor any Preact-specific code. (Component properties)

// once implemented in Portal, can be applied in Vortex

**Comment by prayagd** [comment]
we can do this migration, spoke to Marcel. As Kacper explained this is a day effort thing.

@Sharqiewicz please add estimates to this ticket

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/596?planning-poker) with Zenhub @ebma @Sharqiewicz @TorstenStueber
