### ISSUE TITLE
Add Subwallet using Talisman component

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#6]
As a Subwallet user, I want to connect the SubWallet to portal.

# Acceptance criteria
* On `/Dashboard`
* Clicking on `Connect wallet` opens a pop-up
* In pop-up show
   * `SubWallet` as an option
   * Clicking on `SubWallet`
       * Show all account's from `SubWallet`
       * I should be able to select one account from the list.
* On account selection. Show selected account on top right corner. 

### Notes
* We are using the Talisman components for wallet connect flow. 

# Technical considerations
* Following packages to be used for the integration
    * https://www.npmjs.com/package/@talismn/connect-wallets
    * https://www.npmjs.com/package/@talismn/connect-components
    * https://www.npmjs.com/package/@talismn/connect-ui

**Comment by nicolasdanelon** [comment]
Talisman supports SubWallet if we install this packages:

- https://www.npmjs.com/package/@talismn/connect-wallets
- https://www.npmjs.com/package/@talismn/connect-components
- https://www.npmjs.com/package/@talismn/connect-ui

**Comment by prayagd** [comment]
Currently blocked by https://github.com/TalismanSociety/talisman-connect/pull/21

**Comment by prayagd** [comment]
Closing this looks like talisman has update their component and i can see subwallet added to it. 
<img width="544" alt="Screenshot 2023-03-14 at 6 05 36 PM" src="https://user-images.githubusercontent.com/52105313/225002675-3c99dd58-32e9-4339-a2da-198cd6026caf.png">
