### ISSUE TITLE
State is not saved after reloads

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/portal#61]
After connecting a wallet to the portal, and reloading the page, the wallet is automatically disconnected.

1. Connect a wallet
2. Check that your balance is something
3. Reload the page
4. Check that your wallet is not connected anymore and shows no balance or other functionality related to it.

The expected behavior would be to have the wallet persistent after reloading the page.

Proposed solution:
We should save the global state to (and load it from) local storage. We should also add a way of disconnecting the wallet.

**Comment by nejcm** [comment]
I have a useful hook for local storage I am already using in swap component for persisting the timeout and tolerance. Will make a separate PR for it so you can use it if needed.

**Comment by gonzamontiel** [comment]
Hey @nejcm , I have assigned this one to you from what we spoke earlier, hope that is okay :)
