### ISSUE TITLE
Token approve not working on Forex AMM

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#616]
### Describe the bug

If a user tries to approve token on Forex AMM it does not work

### Reproduction

1. Go to https://deploy-preview-519--rococo-souffle-a625f5.netlify.app/pendulum/nabla/swap-pools
2. Try approving any asset pair and it just keeps loading

### Expected behavior

Token should get approved and button should change to "Swap"

### Screenshots

![image](https://github.com/user-attachments/assets/9313442f-7b1b-4559-bfc8-55d0e759612a)

### Desktop (please complete the following information):

- OS: macOS
- Browser: Chrome

**Comment by ebma** [comment]
Can you try again on the deploy preview @prayagd? This should be fixed now. We just needed to merge the latest changes (dependency upgrades) to that branch.

**Comment by prayagd** [comment]
Yes it works now, closing this ticket
