### ISSUE TITLE
Add pagination to Collator's list

### ISSUE THREAD

**Issue by gonzamontiel** [pendulum-chain/portal#62]
Collators table should include pagination, as shown in the designs:

![Screenshot from 2023-02-28 10-08-31](https://user-images.githubusercontent.com/4713407/221805719-6cdcc8af-348c-42ed-9d21-d6c2fb3fbfc4.png)

### Technical considerations
- There's a related PR that includes a paginated Table (see #64).
- Replace the `<table>` component in `Collators.tsx` with  the paginated component

**Comment by nejcm** [comment]
Will open another PR for this and the pagination one can be merged already
