### ISSUE TITLE
Update menu items with coming soon

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#73]
As a portal user, I should be able to see the upcoming features in the side menu with a coming soon tag.

# Acceptance criteria
* Show Amber, Bridge, Cross-chain options in the side menu
* Add coming soon tag to them
* Make them disabled, they should only be visible but not accessible. 

# Wireframe
https://www.figma.com/file/5up5sghcttBogehUq4255i/App?node-id=2066-1417&t=wW8viFRDexb8HqRW-0

**Comment by prayagd** [comment]
@gonzamontiel Is this ticket clear? Would you need a wireframe for this?

**Comment by gonzamontiel** [comment]
@prayagd pls add a sample image so I can understand how it should look like

**Comment by prayagd** [comment]
@gonzamontiel Sure will get you the designs.

**Comment by gonzamontiel** [comment]
Hey @prayagd , any news on this?

**Comment by prayagd** [comment]
@gonzamontiel This is ready for implementation.

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/73?planning-poker) with Zenhub @gonzamontiel

**Comment by gonzamontiel** [comment]
awesome, just did!
