### ISSUE TITLE
Accept T&Cs pop-up

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#75]
As a portal user, I should accept the T&Cs before connecting and using it. 

# Acceptance criteria
* Show T&Cs pop-up before accessing the portal or connecting the wallet.
* Show link to T&Cs in the pop-up https://pendulumchain.org/legal/portal-terms-and-conditions 
* Store the version of the terms and conditions in local storage on clicking `Agree` 
* If the user has accepted it once and agreement is stored in local storage. No need to show this again while connecting. 

# Wireframe
<img width="381" alt="Screenshot 2023-05-15 at 4 47 19 PM" src="https://github.com/pendulum-chain/portal/assets/52105313/c8ead79b-b4bb-46be-bd8c-40b6773f99a1">

https://www.figma.com/file/5up5sghcttBogehUq4255i/App?node-id=2021-1853&t=wW8viFRDexb8HqRW-0

**Comment by prayagd** [comment]
@gonzamontiel This is ready for development

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/75?planning-poker) with Zenhub @gonzamontiel

**Comment by gonzamontiel** [comment]
ready.

**Comment by erasmus** [comment]
@prayagd I suggest store the _version_ or _date_ of the T&C and in localStorage. On a T&C update, we can then match that against the previously accepted T&C in localStorage and ask for user to accept again. 

Does that make sense?  

![image.png](https://images.zenhubusercontent.com/64089fe03eb1c600220dcdc7/2b673083-f18a-4f5a-afd0-c774d61b292e)

**Comment by prayagd** [comment]
@erasmus yes, will makes changes in the ticket.

**Comment by prayagd** [comment]
@gonzamontiel Updated this ticket and the wireframe.

**Comment by erasmus** [comment]
@prayagd I think we should move this back to backlog, as the AC just changed

**Comment by prayagd** [comment]
@gonzamontiel This is now ready for development.
