### ISSUE TITLE
Dropdown to switch between versions of Portal

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#77]
As a portal user, I should be able to switch between portal version's using a dropdown.

# Acceptance criteria

* Show network dropdown next to wallet connect
* Show three options in this dropdown
    * Amplitude
    * Pendulum
    * Foucoco
* Selecting any option should direct the user to respective URL of the portal
*  Default behaviour of the portal should be https://portal.pendulumchain.org/pendulum/ 

# Wireframe
https://www.figma.com/file/5up5sghcttBogehUq4255i/App?node-id=1782-1232&t=wW8viFRDexb8HqRW-0

**Comment by prayagd** [comment]
@gonzamontiel This is also ready for development.

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/77?planning-poker) with Zenhub @gonzamontiel

**Comment by gonzamontiel** [comment]
ready.
