### ISSUE TITLE
Disable delegate button after delegation

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#81]
### Describe the bug

On the Pendulum version of the portal, i am not able to see my delegation on the table and also the `Delegate` button is not disabled even after i have delegated to one of the collator.

### Reproduction

1. Go to `/collator`
2. Delegate to one of the collator
3. After delegation you can still see the `Delegate` button is enabled

### Expected behavior

The delegate button should be disabled if the user had delegated to one of the collator and also user should be able to see his delegation on the table(this is related to this #80 )

### Screenshots

<img width=“915” alt=“Screenshot 2023-03-14 at 12 59 10 PM” src=“https://user-images.githubusercontent.com/52105313/224926760-4ae9416c-aceb-4623-9dcf-50f6a6b485ac.png”>

### Desktop (please complete the following information):

- OS: iOS
- Browser both chrome[111.0.5563.64] and safari[16.1]

**Comment by prayagd** [comment]
cc @gonzamontiel

**Comment by prayagd** [comment]
@gonzamontiel Any update on this?

**Comment by gonzamontiel** [comment]
I missed this one, but I think it is related with the fix I'm working on for https://github.com/pendulum-chain/portal/issues/82. I will linke the PR when it's ready

**Comment by prayagd** [comment]
@gonzamontiel I see the linked PR is closed, is this also fixed? should we close this?

**Comment by prayagd** [comment]
@gonzamontiel Can you please update?

**Comment by prayagd** [comment]
Closing this as this is fixed.
