### ISSUE TITLE
Show estimated rewards

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#82]
### Describe the bug

User cannot see the estimated rewards.  

### Reproduction

1. Go to `/collator`
2. See the claim section. It does not show the estimated rewards
3. This is the problem on both version Pendulum and Amplitude.

### Expected behavior

If the user has delegated tokens to a collators, he must be able to see the estimated rewards that he is going to recieve.

### Screenshots

![image](https://user-images.githubusercontent.com/52105313/224994205-1349f0c5-73fc-49ee-bb47-bb4718e3fcbf.png)

### Desktop (please complete the following information):

- OS: iOS
- Browser Chrome and safari both

**Comment by prayagd** [comment]
cc @gonzamontiel

**Comment by gonzamontiel** [comment]
Hey, for me it is showing some rewards. Did you wait enough? If you stake some amount, you won't get rewards automatically, but you will need to wait for some time.
  
![Screenshot from 2023-03-15 12 05 33](https://user-images.githubusercontent.com/4713407/225291007-0e6eab92-b14f-4ed5-b33f-d520aad9f103.png)

**Comment by gonzamontiel** [comment]
were you able to check it out @prayagd ?

**Comment by prayagd** [comment]
![image](https://user-images.githubusercontent.com/52105313/225659891-2137394c-b624-4ed8-87ec-65916af48b92.png)

**Comment by ebma** [comment]
I can also not see any estimated reward on Foucoco for the first signatory account (see that one notion page with signer keys). Maybe this is a depencendy issue in a `useState` hook and it just does not rerender properly once the account connects? 
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/6690623/226595708-8d09c13f-90b5-4d2e-9a67-c779bec92269.png">

**Comment by prayagd** [comment]
@gonzamontiel Can you please update about this?
