### ISSUE TITLE
Add responsiveness on portal for mobile devices

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/portal#94]
### Context / Issue
The current portal UI on mobile devices is not acceptable as a lot of features do not work.

### Requirement / User Story
As a mobile user, I want to the portal website to be responsive to my device, so that I can use all the features of the portal.

### Solution / Tasks

As an interim solution, since we don't have any designs for this, we first try to make every feature 'usable' meaning that users can access/see all information and can interact with every button, even though the resulting user experience might still not be ideal. To do that:
- [ ] Introduce responsive design in the best possible way, without requiring new designs.
This means that the existing UI elements are probably just re-arranged and re-scaled if needed. 
- [ ] To test the responsiveness of the current version of the portal.

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/94?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by prayagd** [comment]
@gonzamontiel IMO we should start with collator dashboard for mobile design wdyt? If you agree will let Marina to know to get started with the designs then.

**Comment by gonzamontiel** [comment]
Okay I agree. Honestly I didn't start working on it yet, so if we are getting designs, we can split this ticket into the different sections to adapt. let's discuss
