### ISSUE TITLE
Fetch collator identities

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#96]
As a delegator i should be able to see the collator identities on the collator dashboard

# Acceptance criteria
* Show the onchain identity of the collators in the list of collators for both Pendulum and Amplitude. 
* If identity no present then show the collator address.

**Comment by prayagd** [comment]
@gonzamontiel This is ready for development, Please let me know if anything unclear or missing.

**Comment by prayagd** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/96?planning-poker) with Zenhub @gonzamontiel

**Comment by gonzamontiel** [comment]
So this is about using the identity pallet right? @ebma I guess this is done by calling identity.identityOf() for each the collator in the table. pls correct me if I'm wrong.

**Comment by prayagd** [comment]
Yes this is about the identity pallet.

**Comment by gonzamontiel** [comment]
Digging into pallet'sidentity more, I noticed that the response is actually an object like following:
```
{
      judgements: []
      deposit: 10,000,000,000,000
      info: {
        additional: []
        display: {
          Raw: 0xf09fa78a2049636562657267204e6f64657320f09fa78a
        }
        legal: None
        web: None
        riot: {
          Raw: @icebergnodes:matrix.org
        }
        email: {
          Raw: info@icebergnodes.com
        }
        pgpFingerprint: null
        image: None
        twitter: {
          Raw: @IcebergNodes
        }
      }
    }
```

I could add some logic to decide which field to take first, but I would need some more info in which would be the most used one. Is it twitter? riot? email? Please  @prayagd, let's complete the info so I can continue.

**Comment by gonzamontiel** [comment]
You're right, I can decode it. But I still left the fallback: display > email > twitter > address

**Comment by prayagd** [comment]
Great, that is great approach
