### ISSUE TITLE
Submitting a transaction with a locally stored account not working

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/portal#97]
### Describe the bug

Signing transactions is not working when using the wallet account saved to local storage. 
The problem is that when saving it to localStorage, the `signer` class cannot be recreated properly since it's not just raw data but a class instance.

### Reproduction

Connect to a wallet account. Reload the page. Wait until the account is loaded from storage again. Try to sign and submit an extrinsic with this account. This will fail and complain about the invalid signer. This occurred when testing the spacewalk UI.

### Expected behavior

I should be able to sign and submit a transaction with the account that is restored from local storage.

### Screenshots

<img width="766" alt="image" src="https://user-images.githubusercontent.com/6690623/229570587-520e6793-a94d-40a8-bd5a-60c26daee967.png">

See the difference in the `signer` field when using the 'restored' account from `localStorage` vs when freshly connecting with the wallet-connect button.
![image](https://user-images.githubusercontent.com/6690623/229570618-2a6643a9-d431-427d-be8a-13002b9d95d2.png)

**Comment by gonzamontiel** [comment]
@prayagd did you have any input from Talisman here?

**Comment by prayagd** [comment]
@gonzamontiel Thank you for reminding me, unfortunately it slipped from my mind. Have followed up now. Will update once i get a reply.

**Comment by gonzamontiel** [comment]
Closing this since its fixed in #98
